template:
  path: cert.yaml
  type: file

parameters:
  # HostedZoneId: !ssm_parameter /uc3/dmp/hub/dev/HostedZoneId
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone

  Domain: !stack_attr sceptre_user_data.domain

  Env: !stack_attr sceptre_user_data.env
