template:
  path: cert.yaml
  type: file

parameters:
  HostedZoneId: !ssm_parameter /uc3/dmp/hub/dev/HostedZoneId

  Domain: !stack_attr sceptre_user_data.domain

  Env: !stack_attr sceptre_user_data.env
