template:
  path: 'route53.yaml'
  type: 'file'

parameters:
  HostedZoneId: !ssm_parameter /uc3/dmp/hub/dev/HostedZoneId

  Domain: 'ui.dmphub.uc3dev.cdlib.net'
  RecordType: 'A'

  TargetName: !stack_output dev/regional/alb.yaml::AlbDnsName
  TargetHostedZoneId: !stack_output dev/regional/alb.yaml::AlbCanonicalHostedZoneId

  # We need to tell it which region our ALB lives in
  TargetRegion: 'us-west-2'

  SetIdentifier: 'dmsp-prototype'
