template:
  path: 'route53.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone

  Env: !stack_attr sceptre_user_data.env
  Domain: !stack_attr sceptre_user_data.domain
  RecordType: 'A'

  TargetName: !stack_output dev/global/cloudfront.yaml::CloudfrontDistroDomainName
  # This HostedZone is the default for ALL CloudFront Distributions
  TargetHostedZoneId: 'Z2FDTNDATAQYW2'

  SetIdentifier: 'Slartibartfast'
