template:
  path: 'route53.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone

  Domain: 'ui.dmptool.uc3dev.cdlib.net'
  RecordType: 'A'

  TargetName: !stack_output tool/dev/alb.yaml::AlbDnsName
  TargetHostedZoneId: !stack_output tool/dev/alb.yaml::AlbCanonicalHostedZoneId

  # We need to tell it which region our ALB lives in
  TargetRegion: 'us-west-2'

  SetIdentifier: 'dmptool'
