template:
  path: 'waf.yaml'
  type: 'file'

parameters:
  # Specifies whether this is for a CLOUDFRONT distribution or for a REGIONAL application
  Scope: 'CLOUDFRONT'
  # Whether AWS WAF should store a sampling of the web requests that matched the rules.
  SampledRequestsEnabled: 'true'
  # Whether WAF sends metrics to Amazon CloudWatch.
  CloudWatchMetricsEnabled: 'true'
  # S3 Bucket for WAF logs
  S3WafLogsBucketARN: !stack_output dev/s3.yaml::S3WafLogsBucketARN
