# Sceptre will create an S3 bucket to store your CloudFormation templates. Define the name here or
# provide the name of an existing bucket.
template_bucket_name: 'uc3-dmp-tool-cf-bucket'

# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
#
# THESE DO NOT CASCADE, need to define in subdirectories as well!
sceptre_user_data:
  vpc_id: !stack_output_external cdl-uc3-dev-vpc-stack::vpc

  public_subnet_a: !stack_output_external cdl-uc3-dev-defaultsubnet-stack::defaultsubnet2a

  app_name: 'dmptool'

# Stack tags are attached to every AWS resource created by these CloudFormation templates
# with the exception of the Lambda functions and layers which are managed by AWS SAM.
#
# THESE DO NOT CASCADE, need to define in subdirectories as well!
stack_tags:
  Program: 'uc3'
  Service: 'dmp'
  Subservice: 'tool'
  CodeRepo: 'https://github.com/CDLUC3/dmsp_aws_prototype'
  Contact: 'briley'
