
# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
sceptre_user_data:
  vpc_id: !stack_output_external cdl-uc3-prd-vpc-stack::vpc

  public_subnets:
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2a
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2b
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2c

  # We sometimes need to access the subnets individually
  public_subnet_a: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2a
  public_subnet_b: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2b
  public_subnet_c: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2c

  hosted_zone: !ssm /uc3/dmp/hub/prd/HostedZoneId

  env: 'prd'
  domain: 'dmphub.uc3prd.cdlib.net'
  ssm_path: '/uc3/dmp/hub/prd/'
