# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2'

gem 'text'

# UC3 Managed Gems
gem 'uc3-dmp-api-core'
gem 'uc3-dmp-citation'
gem 'uc3-dmp-cloudwatch'
gem 'uc3-dmp-dynamo'
gem 'uc3-dmp-event-bridge'
gem 'uc3-dmp-external-api'
gem 'uc3-dmp-id'
