# Sceptre will create an S3 bucket to store your CloudFormation templates. Define the name here or
# provide the name of an existing bucket.
#
template_bucket_name: 'uc3-dmp-hub-cf-bucket-cdluc3prd'

# Stack tags are attached to every AWS resource created by these CloudFormation templates
# with the exception of the Lambda functions and layers which are managed by AWS SAM.
#
stack_tags:
  Program: 'uc3'
  Service: 'dmp'
  Subservice: 'hub'
  Environment: 'prd'
  CodeRepo: 'https://github.com/CDLUC3/dmsp_aws_prototype'
  Contact: 'briley'

# In the cdl-uc3-prd account devs must call cloudformation using a service role
cloudformation_service_role: !ssm /uc3/prd/CfnServiceRoleArn
