template:
  path: 'alb.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  HostedZoneId: !ssm /uc3/dmp/HostedZoneId

  CertificateArn: !stack_output tool/dev/cert.yaml::CertificateArn

  WafArn: !stack_output tool/dev/waf.yaml::WafArn

  S3LogBucketArn: !stack_output tool/s3.yaml::S3LogBucketArn
  S3LogBucketId: !stack_output tool/s3.yaml::S3LogBucketId

  Domain: !stack_attr sceptre_user_data.domain

  AppName: !stack_attr sceptre_user_data.app_name
