template:
  path: cert.yaml
  type: file

parameters:
  HostedZoneId: !ssm /uc3/dmp/HostedZoneId

  Domain: !stack_attr sceptre_user_data.domain

  Env: !stack_attr sceptre_user_data.env

  AppName: !stack_attr sceptre_user_data.app_name
