template:
  path: 'ecs-cluster.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  AlbSecurityGroupId: !stack_output tool/dev/alb.yaml::AlbSecurityGroupId

  DbSecurityGroupId: !stack_output tool/dev/rds.yaml::DbSecurityGroupId

  CacheSecurityGroupId: !stack_output tool/dev/backend/cache.yaml::CacheSecurityGroupId

  DbPort: !stack_output tool/dev/rds.yaml::DbPort
