# We need to override the default us-west-2 region here for our Backup region
region: 'us-east-2'

# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
sceptre_user_data:
  env: 'stg'
