template:
  path: 'alb.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone

  CertificateArn: !stack_output tool/stg/acm.yaml::CertificateArn

  WafArn: !stack_output tool/stg/waf.yaml::WafArn

  S3LogBucketArn: !stack_output tool/stg/s3-logs.yaml::S3BucketARN
  S3LogBucketId: !stack_output tool/stg/s3-logs.yaml::S3BucketID

  Domain: !stack_attr sceptre_user_data.domain

  AppName: !stack_attr sceptre_user_data.app
