template:
  path: 'ecs-cluster.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  AlbSecurityGroupId: !stack_output tool/stg/alb.yaml::AlbSecurityGroupId

  DbSecurityGroupId: !stack_output tool/stg/rds.yaml::DbSecurityGroupId

  CacheSecurityGroupId: !stack_output tool/stg/cache.yaml::CacheSecurityGroupId

  DbPort: !stack_output tool/stg/rds.yaml::DbPort
