template:
  path: 'rds.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  # If you have an existing RDS snapshot of your DB, you can include it here and CF will
  # restore that snapshot. If not, just leave this commented out and Docker will initialize the DB
  # DBSnapshot: 'Snapshot ARN'

  # G series is Graviton
  DbInstanceType: 'db.t4g.small'
  DbSizeGb: '20'
  StorageType: 'gp3'

  # Valid options are based on the DB engine.
  # Use this to see what versions are availanle: `aws rds describe-db-engine-versions --default-only --engine mysql`
  DbEngine: 'mysql'
  DbEngineVersion: '8.4.4'
  LicenseModel: 'general-public-license'

  DbBackupRetentionDays: '35'
  PreferredMaintenanceWindow: 'sat:08:00-sat:08:30'
  PreferredBackupWindow: '07:00-07:30'

  MultiAz: 'true'

  DbName: !stack_attr sceptre_user_data.app
  DbMasterUsername: 'root'
  DbMasterPassword: !ssm /uc3/dmp/tool/stg/DbPassword
  DbPort: '3306'
