require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  # Show the name of the cops being voilated in the feedback
  DisplayCopNames: true
  DisplayStyleGuide: true

  # Automatically add any new Cops to this file and enable them
  NewCops: enable

  # Cache the results for faster processing
  UseCache: true

  # Commenting out because we use shared CDL account for RubyGems and MFA doesn't work
  Exclude:
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
