template:
  path: 'alb.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone_id

  CertificateArn: !stack_output dev/global/cert.yaml::CertificateArn

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: 'tool'

  AppName: 'dmptool'
