template:
  path: 'chatbot.yaml'
  type: 'file'

parameters:
  ConfigurationNameParameter: 'my-slack-config'
  SlackCodestarConnectionArnParameter: !ssm_parameter '/uc3/dmp/hub/dev/SlackCodestarConnection'
  LoggingLevelParameter: 'ERROR'
  SlackChannelIdParameter: C074WLW59EF
  SlackWorkspaceIdParameter: T02AJMWEJ