template:
  path: 'codepipeline.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodeBuildProjectName: !stack_output dev/regional/codebuild-frontend.yaml::CodeBuildProjectId

  RepositoryName: 'CDLUC3/dmsp_frontend_prototype'
  BranchToMonitor: 'development'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'

  # Comment these 2 ECS parameters out the first time you build the environment. The ECS services
  # require an image already be in the ECR, but this Pipeline builds those images!
  EcsCluster: !stack_output dev/regional/ecs-cluster.yaml::EcsFargateClusterId
  EcsServiceName: !stack_output dev/regional/ecs-frontend.yaml::EcsServiceName

  ChatbotArn: !stack_output dev/regional/chatbot.yaml::SlackChannelConfigurationArn
