template:
  path: 'pipeline-dmptool.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodeBuildProjectName: !stack_output dev/regional/codebuild.yaml::CodeBuildProject

  RepositoryName: 'CDLUC3/dmsp_prototype'
  BranchToMonitor: 'main'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'
