template:
  path: 'codebuild-rails.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  EcrRepositoryArn: !stack_output dev/regional/ecr.yaml::EcrRepositoryArn
  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri
  EcrRepositoryName: !stack_output dev/regional/ecr.yaml::EcrRepositoryName

  S3ArtifactBucketArn: !stack_output dev/regional/s3.yaml::S3PrivateBucketArn
  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodePipelineLogGroupArn: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupArn
  CodePipelineLogGroupName: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupName

  CodeBuildEnvironmentType: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType: 'BUILD_GENERAL1_SMALL'
  # This is AL2023
  CodeBuildEnvironmentImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
  CodeBuildTimeout: '15'
