template:
  path: 'codepipeline-rails.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodeBuildProjectName: !stack_output dev/regional/codebuild-rails.yaml::CodeBuildProjectId

  RepositoryName: 'CDLUC3/dmsp_rails_prototype'
  BranchToMonitor: 'development'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'
