template:
  path: 'codepipeline-backend.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodeBuildProjectName: !stack_output dev/regional/codebuild-backend.yaml::CodeBuildProjectId

  RepositoryName: 'CDLUC3/dmsp_backend_prototype'
  BranchToMonitor: 'development'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'

  EcsCluster: !stack_output dev/regional/ecs-cluster.yaml::EcsFargateClusterId
  EcsServiceName: !stack_output dev/regional/ecs-backend.yaml::EcsServiceName
