template:
  path: 'codebuild-ui.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  S3ArtifactBucketArn: !stack_output dev/regional/s3.yaml::S3PrivateBucketArn
  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodePipelineLogGroupArn: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupArn
  CodePipelineLogGroupName: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupName

  S3DeployBucketArn: !stack_output dev/regional/s3.yaml::S3CloudFrontBucketArn
  S3DeployBucketId: !stack_output dev/regional/s3.yaml::S3CloudFrontBucketId

  CloudFrontDistributionId: !stack_output dev/global/cloudfront.yaml::CloudfrontDistroId

  CodeBuildEnvironmentType: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType: 'BUILD_GENERAL1_SMALL'
  CodeBuildEnvironmentImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
  CodeBuildTimeout: '15'
