template:
  path: 'codebuild-backend.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  # RouteTableId: !stack_output_external cdl-uc3-dev-vpc-stack::vpcrt
  # Subnets: !stack_attr sceptre_user_data.public_subnets

  Program: !stack_attr stack_tags.Program
  Service: !stack_attr stack_tags.Service
  Subservice: !stack_attr stack_tags.Subservice
  CodeRepo: !stack_attr stack_tags.CodeRepo
  Contact: !stack_attr stack_tags.Contact

  Env: !stack_attr sceptre_user_data.env

  EcrRepositoryArn: !stack_output dev/regional/ecr.yaml::EcrRepositoryArn
  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri
  EcrRepositoryName: !stack_output dev/regional/ecr.yaml::EcrRepositoryName

  # S3ArtifactBucketAlias: !stack_output dev/regional/s3.yaml::S3PipelineArtifactAccessPointAlias
  S3ArtifactBucketArn: !stack_output dev/regional/s3.yaml::S3PrivateBucketArn
  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  # DbSecurityGroupId: !stack_output dev/regional/rds.yaml::DbSecurityGroupId

  CodePipelineLogGroupArn: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupArn
  CodePipelineLogGroupName: !stack_output dev/regional/cloudwatch.yaml::CodePipelineLogGroupName

  DbHost: !stack_output dev/regional/rds.yaml::DbAddress
  DbPort: !stack_output dev/regional/rds.yaml::DbPort
  DbName: !stack_output dev/regional/rds.yaml::DbName
  DbUsername: !ssm_parameter /uc3/dmp/hub/dev/DbUsername
  DbPassword: !ssm_parameter /uc3/dmp/hub/dev/DbPassword

  # We want Apollo server to run in development mode in this env so that the Explorer works
  NodeEnv: 'development'

  CodeBuildEnvironmentType: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType: 'BUILD_GENERAL1_SMALL'
  # This is AL2023
  CodeBuildEnvironmentImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
  CodeBuildTimeout: '15'
