template:
  path: 'cognito.yaml'
  type: 'file'

dependencies:
  - 'dev/regional/route53.yaml'

parameters:
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone_id

  Domain: !stack_attr sceptre_user_data.domain
  # TODO: Remove this once the new HostedZone is in place
  Subdomain: !stack_attr sceptre_user_data.subdomain

  CertificateArn: !stack_output dev/regional/cert.yaml::CognitoCertificateArn

  UserPoolClientName: 'default'

  OnlyAllowAdminsToCreateUsers: 'false'
  UnusedAccountValidityDays: '14'
  MinimumPasswordLength: '8'
