template:
  path: 'cognito.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone_id

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: 'auth'
  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  CertificateArn: !stack_output dev/global/cert.yaml::CertificateArn

  OnlyAllowAdminsToCreateUsers: 'false'
  UnusedAccountValidityDays: '14'
  MinimumPasswordLength: '8'
