template:
  path: 'cognito-clients.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  UserPoolId: !stack_output dev/regional/cognito.yaml::UserPoolId

  UserPoolDomain: !stack_output dev/regional/cognito.yaml::UserPoolDomain

  UiClientName: 'dmphub'

  DmptoolClientName: 'dmptool'

  DmptoolCallbackUri: 'https://dmptool-dev.cdlib.org/callback'

  TokenValidityUnits: 'minutes'
  AccessTokenValidity: '10'
  AuthSessionValidatyMinutes: '3'
  IdTokenValidity: '7'
  RefreshTokenValidity: '10080'
