template:
  path: dynamo.yaml
  type: file

parameters:
  SsmPath: !stack_attr sceptre_user_data.ssm_path

  # Dynamo settings
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  DynamoTableClass: 'STANDARD'
  DynamoEnableContributorInsights: 'true'
  DynamoEnablePointInTimeRecovery: 'false'
  DynamoBillingMode: 'PROVISIONED'
  DynamoReadCapacityUnits: '16'
  DynamoWriteCapacityUnits: '60'
