template:
  path: 'ecs-backend.yaml'
  type: 'file'

dependencies:
  - dev/global/dmsp-backend-route53.yaml

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env

  AppName: 'DMSP-backend-dev'

  SessionSecret: !ssm_parameter /uc3/dmp/prototype/dev/SessionSecret

  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri

  AlbTargetGroupArn: !stack_output dev/regional/alb.yaml::AlbTargetGroupArn

  AlbSecurityGroupId: !stack_output dev/regional/alb.yaml::AlbSecurityGroupId

  DynamoTableName: !stack_output dev/regional/dynamo.yaml::DynamoTableName

  HelpdeskEmail: !ssm_parameter /uc3/dmsp/prototype/dev/HelpdeskEmail
