template:
  path: 'ecs-backend.yaml'
  type: 'file'

parameters:
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env

  AppName: !stack_attr sceptre_user_data.app_name
  DomainName: !stack_attr sceptre_user_data.domain
  ContainerName: !stack_attr sceptre_user_data.backend_server_container_name

  DefaultAffiliationRor: 'https://ror.org/00dmfq477'

  EcsDesiredServiceCount: '2'

  AppPort: '4000'

  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri

  EcrImageTag: 'apollo-latest'

  EcsClusterId: !stack_output dev/regional/ecs-cluster.yaml::EcsFargateClusterId
  EcsTaskExecutionRoleId: !stack_output dev/regional/ecs-cluster.yaml::EcsFargateExecutionRoleId
  EcsSecGrpId: !stack_output dev/regional/ecs-cluster.yaml::EcsFargateSecGrp

  AlbTargetGroupArn: !stack_output dev/regional/alb.yaml::ApolloServerTargetGroupArn

  AlbSecGrpId: !stack_output dev/regional/alb.yaml::AlbSecurityGroupId

  CpuSize: '2048'
  MemorySize: '4096'

  StartTimeout: '30'
  HealthCheckGracePeriod: '30'
  MinimumHealthyContainerPercentage: '50'
  MaximumHealthyContainerPercentage: '200'
  StopTimeout: '30'

  LogLevel: 'debug'
  CognitoClientId: !stack_output dev/regional/cognito.yaml::DmspUserPoolClientId
  CognitoClientSecret: !stack_output dev/regional/cognito.yaml::DmspUserPoolClientSecret

  DmpIdBaseUrl: !ssm /uc3/dmp/hub/dev/EzidBaseUrl
  DmpIdShoulder: !ssm /uc3/dmp/hub/dev/EzidShoulder

  BcryptSaltRounds: '10'
  HashTokenSecret: !ssm /uc3/dmp/tool/dev/CacheHashSecret
  RestDataSourceCacheTtl: '180' # 2 minutes

  NodeEnv: 'staging'

  JwtSecret: !ssm /uc3/dmp/tool/dev/JWTSecret
  JwtTtl: '1800000' # 30 minutes (in milliseconds)
  JwtRefreshSecret: !ssm /uc3/dmp/tool/dev/JWTRefreshSecret
  JwtRefreshTtl: '86400000' # 24 hours (in milliseconds)

  CsrfLength: '64'
  CsrfTtl: '3600' # 1 hour (in seconds)

  DbConnectionLimit: '5'
  DbHost: !stack_output dev/regional/rds.yaml::DbAddress
  DbPort: !stack_output dev/regional/rds.yaml::DbPort
  DbName: !stack_output dev/regional/rds.yaml::DbName
  DbUsername: !ssm /uc3/dmp/hub/dev/DbUsername
  DbPassword: !ssm /uc3/dmp/hub/dev/DbPassword

  CacheHost: !stack_output dev/regional/redis-backend.yaml::RedisReaderHost
  CachePort: !stack_output dev/regional/redis-backend.yaml::RedisReaderPort
  CacheConnectTimeout: '10000' # 10 seconds

  SesEndpoint: !ssm /uc3/dev/SesEndpoint
  SesAccessKeyId: !ssm /uc3/dmp/tool/dev/SesAccessKeyId
  SesAccessKeySecret: !ssm /uc3/dmp/tool/dev/SesAccessKeySecret
  SesBouncedEmailBucket: !ssm /uc3/dev/SesBouncedEmailBucket
  DoNotReplyEmail: !ssm /uc3/dmp/tool/dev/DoNotReplyEmail
  HelpdeskEmail: !ssm /uc3/dmp/tool/dev/HelpdeskEmail

  UseMockData: 'true'
