template:
  path: 'ecs-cluster.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  AlbSecurityGroupId: !stack_output dev/regional/alb.yaml::AlbSecurityGroupId

  DbSecurityGroupId: !stack_output dev/regional/rds.yaml::DbSecurityGroupId

  CacheSecurityGroupId: !stack_output dev/regional/redis-backend.yaml::RedisCacheSecurityGroupID

  DbPort: !stack_output dev/regional/rds.yaml::DbPort

  CachePort: !stack_output dev/regional/redis-backend.yaml::RedisReaderPort
