template:
  path: 'ecs.yaml'
  type: 'file'

dependencies:
  - dev/global/dmsp-rails-route53.yaml

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  DomainName: !stack_attr sceptre_user_data.domain

  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri
  EcrRepositoryName: !stack_output dev/regional/ecr.yaml::EcrRepositoryName

  S3CloudFrontBucketId: !stack_output dev/regional/s3.yaml::S3CloudFrontBucketId

  AlbTargetGroupArn: !stack_output dev/regional/alb.yaml::AlbTargetGroupArn
  AlbDnsName: !stack_output dev/regional/alb.yaml::AlbDnsName
  AlbSecurityGroupId: !stack_output dev/regional/alb.yaml::AlbSecurityGroupId

  DbSecurityGroupId: !stack_output dev/regional/rds.yaml::DbSecurityGroupId

  DynamoTableName: !stack_output dev/regional/dynamo.yaml::DynamoTableName

  RailsMasterKey: !ssm_parameter /uc3/dmsp/prototype/dev/RailsMasterKey
  DoiShoulder: !ssm_parameter /uc3/dmsp/prototype/dev/DoiShoulder
  DoiBaseUrl: !ssm_parameter /uc3/dmsp/prototype/dev/DoiBaseUrl
  HelpdeskEmail: !ssm_parameter /uc3/dmsp/prototype/dev/HelpdeskEmail

  # Set this value to '0' when you first create the stack otherwise the stack creation will
  # hang indefinitely on `EcsService AWS::ECS::Service CREATE_IN_PROGRESS Resource creation Initiated`
  # see: https://stackoverflow.com/questions/32727520/cloudformation-template-for-creating-ecs-service-stuck-in-create-in-progress
  #
  # After it is created, change the value to a positive integer
  EcsDesiredServiceCount: '2' # '0'
  AppName: 'dmsp-prototype-dev'
  RailsEnv: 'awsdev'
  RailsLogLevel: 'debug'
  DynamoPoolSize: '5'
  DynamoTimeout: '5'
  DoNotReplyEmail: 'do-not-reply-dmsp-prototype-dev@udmphub.uc3dev.cdlib.net'
