template:
  path: eventbridge.yaml
  type: file

parameters:
  SsmPath: !stack_attr sceptre_user_data.ssm_path

  DomainName: !stack_attr sceptre_user_data.domain

  # Log and Archive retention
  LogRetentionDays: '3'
  ArchiveRetentionDays: '7'
