template:
  path: 'lambda-iam.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  OpenSearchDomainArn: !stack_output dev/regional/opensearch.yaml::OpenSearchDomainArn

  DmpTableArn: !stack_output dev/regional/dynamo.yaml::DynamoTableArn

  TypeaheadTableArn: !stack_output dev/regional/dynamo.yaml::TypeaheadTableArn

hooks:
  after_create:
    # Create the dependent Lambdas
    - !cmd 'cd ./src/lambdas/layers/baseline && ruby sam_build_deploy.rb dev true true'

    - !cmd 'cd ./src/lambdas/indexers/dmp && ruby sam_build_deploy.rb dev true true info'
    - !cmd 'cd ./src/lambdas/indexers/typeahead && ruby sam_build_deploy.rb dev true true info'

    - !cmd 'cd ./src/lambdas/harvesters/ror && ruby sam_build_deploy.rb dev true true info'

    - !cmd 'cd ./src/sam && ruby sam_build_deploy.rb dev true true debug'

  after_update:
    # Update the dependent Lambdas
    - !cmd 'cd ./src/lambdas/layers/baseline && ruby sam_build_deploy.rb dev true true'

    - !cmd 'cd ./src/lambdas/indexers/dmp && ruby sam_build_deploy.rb dev true true info'
    - !cmd 'cd ./src/lambdas/indexers/typeahead && ruby sam_build_deploy.rb dev true true info'

    - !cmd 'cd ./src/lambdas/harvesters/ror && ruby sam_build_deploy.rb dev true true info'

    - !cmd 'cd ./src/sam && ruby sam_build_deploy.rb dev true true debug'

  before_delete:
    # Delete any dependent Lambdas
    - !cmd 'cd ./src/lambdas/indexers/dmp && ruby sam_build_deploy.rb dev false false'
    # - !cmd 'cd ./src/lambdas/indexers/typeahead && ruby sam_build_deploy.rb dev false false'

    - !cmd 'cd ./src/lambdas/harvesters/ror && ruby sam_build_deploy.rb dev false false'

    - !cmd 'cd ./src/sam && ruby sam_build_deploy.rb dev false false'

    - !cmd 'cd ./src/lambdas/layers/baseline && ruby sam_build_deploy.rb dev false false'
