template:
  path: 'lambda-vpc.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  VpcId: !stack_attr sceptre_user_data.vpc_id

  RdsSecGrpId: !stack_output dev/regional/rds.yaml::DbSecurityGroupId
