template:
  path: 'lambda-iam.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  OpenSearchDomainArn: !stack_output dev/regional/opensearch.yaml::OpenSearchDomainArn

  EventBusArn: !stack_output dev/regional/eventbridge.yaml::EventBusArn

  DmpTableArn: !stack_output dev/regional/dynamo.yaml::DynamoTableArn
