template:
  path: 'lambda-iam.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path
  Domain: !stack_attr sceptre_user_data.domain

  # OpenSearchDomainArn: !stack_output dev/regional/opensearch.yaml::OpenSearchDomainArn

  EventBusArn: !stack_output dev/regional/eventbridge.yaml::EventBusArn

  DmpTableArn: !stack_output dev/regional/dynamo.yaml::DynamoTableArn

  IndexTableArn: !stack_output dev/regional/dynamo-index-table.yaml::DynamoIndexTableArn

  ExternalDataTableArn: !stack_output dev/regional/dynamo-external-data-table.yaml::ExternalDataDynamoTableArn
