template:
  path: opensearch.yaml
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  CognitoUserPoolId: !stack_output dev/regional/cognito.yaml::UserPoolId
  CognitoIdentityPoolId: !stack_output dev/regional/cognito.yaml::IdentityPoolId
  CognitoOpenSearchRoleArn: !stack_output dev/regional/cognito.yaml::OpenSearchCognitoRoleArn

  OSLogsDomainId: !stack_output_external Uc3OpsOpensearchStack::domainName
  OSLogsDomainEndpoint: !stack_output_external Uc3OpsOpensearchStack::domainEndpoint

  LogRetentionDays: '14'
