template:
  path: 'pipeline-config.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  Env: !stack_attr sceptre_user_data.env

  LogRetentionDays: '14'

  # We need to add a special tag to the CodeBuild SecGroup so that it does not
  # generate an alarm after the EC2 instance used by CodeBuild is removed.
  # So, we need to pass in our normal tags here so that the SecGroup will have all of them
  ProgramTag: !stack_attr stack_tags.Program
  ServiceTag: !stack_attr stack_tags.Service
  SubserviceTag: !stack_attr stack_tags.Subservice
  CodeRepoTag: !stack_attr stack_tags.CodeRepo
  ContactTag: !stack_attr stack_tags.Contact
