template:
  path: 'pipeline-hub.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.private_subnets

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3CloudFrontBucketId: !stack_output dev/regional/s3.yaml::S3CloudFrontBucketId
  CloudFrontDistroId: !stack_output dev/global/cloudfront.yaml::CloudfrontDistroId

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId
  S3LogBucketId: !stack_output dev/regional/s3.yaml::S3LogBucketId

  SnsTopicEmailArn: !stack_output dev/regional/sqs.yaml::SnsCodeBuildTopicEmailArn
  CodeBuildEmail: !stack_attr sceptre_user_data.code_build_email

  CodeBuildSecurityGroupId: !stack_output dev/regional/pipeline-config.yaml::PipelineSecurityGroupId
  IamPipelineRoleArn: !stack_output dev/regional/pipeline-config.yaml::IamPipelineRoleArn
  PipelineLogGroupName: !stack_output dev/regional/pipeline-config.yaml::PipelineLogGroupName
  PipelineLogGroupArn: !stack_output dev/regional/pipeline-config.yaml::PipelineLogGroupArn

  # The repository branchs the CodePipelines should monitor for changes.
  RepositoryName: 'CDLUC3/dmp-hub-ui'
  BranchToMonitor: 'main'
  SourceOutputArtifactFormat: 'CODE_ZIP'
