template:
  path: 'pipeline-dmptool.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.private_subnets

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  EcrRepositoryUri: !stack_output dev/regional/ecr.yaml::EcrRepositoryUri
  EcrRepositoryName: !stack_output dev/regional/ecr.yaml::EcrRepositoryName

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId

  # EcsClusterName: !stack_output dev/regional/ecs.yaml::EcsFargateClusterId
  # EcsServiceName: !stack_output dev/regional/ecs.yaml::EcsServiceName

  AlbTargetGroupFullName: !stack_output dev/regional/alb.yaml::AlbTargetGroupFullName

  # TODO: update this once we've got the domain names moved over and we consolidate around
  #       the dmptool-dev.cdlib.org domain name
  SsmPath: '/uc3/dmp/tool/dev/' # !stack_attr sceptre_user_data.ssm_path

  CodeBuildSecurityGroupId: !stack_output dev/regional/pipeline-config.yaml::PipelineSecurityGroupId
  IamPipelineRoleArn: !stack_output dev/regional/pipeline-config.yaml::IamPipelineRoleArn
  PipelineLogGroupName: !stack_output dev/regional/pipeline-config.yaml::PipelineLogGroupName
  PipelineLogGroupArn: !stack_output dev/regional/pipeline-config.yaml::PipelineLogGroupArn

  # The repository branchs the CodePipelines should monitor for changes.
  RepositoryName: 'CDLUC3/dmptool'
  BranchToMonitor: 'v5.0.1-beta'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'
