template:
  path: 'pipeline.yaml'
  type: 'file'

dependencies:
  - dev/global/route53.yaml

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.private_subnets

  DomainName: !stack_attr sceptre_user_data.domain
  Subdomain: !stack_attr sceptre_user_data.subdomain
  Env: !stack_attr sceptre_user_data.env

  # We need to add a special tag to the CodeBuild SecGroup so that it does not
  # generate an alarm after the EC2 instance used by CodeBuild is removed.
  # So, we need to pass in our normal tags here so that the SecGroup will have all of them
  Program: !stack_attr stack_tags.Program
  Service: !stack_attr stack_tags.Service
  Subservice: !stack_attr stack_tags.Subservice

  LogRetentionDays: '14'

  # The repository branch the CodePipeline should monitor for changes.
  CodePipelineRepositoryName: 'CDLUC3/dmp-hub-ecs'
  CodePipelineBranchToMonitor: 'main'

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output dev/regional/s3.yaml::S3PrivateBucketId
  S3LogBucketId: !stack_output dev/regional/s3.yaml::S3LogBucketId
