template:
  path: 'rds.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env

  # If you have an existing RDS snapshot of your DB, you can include it here and CF will
  # restore that snapshot. If not, just leave this commented out and Docker will initialize the DB
  # DBSnapshot: 'Snapshot ARN'

  DbInstanceType: 'db.t3.micro'
  DbSizeGb: '20'

  # Valid options are based on the DB engine.
  # Use this to see what versions are availanle: `aws rds describe-db-engine-versions --default-only --engine mysql`
  DbEngine: 'mysql'
  DbEngineVersion: '8.0.33'

  DbBackupRetentionDays: '7'

  DbName: 'dmsp'
  DbMasterUsername: 'root'
  DbPort: '3306'
