template:
  path: 'rds.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env

  # If you have an existing RDS snapshot of your DB, you can include it here and CF will
  # restore that snapshot. If not, just leave this commented out and Docker will initialize the DB
  # DBSnapshot: 'arn:aws:rds:us-west-2:671846987296:snapshot:uc3-dmp-roadmap-initial'

  DbInstanceType: 'db.t3.micro'
  # DbSizeGb: '20'

  # Valid options are based on the DB engine.
  # Use this to see what versions are availanle: `aws rds describe-db-engine-versions --default-only --engine postgres`
  DbEngine: 'postgres'
  DbEngineVersion: '15.4'

  DbBackupRetentionDays: '7'

  DbName: 'dmsp'
  DbMasterUsername: 'postgres'
  DbPort: '5432'
