template:
  path: s3.yaml
  type: file

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id

  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  LogBucketObjectLifeSpan: '30'