# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in the gemspec
gemspec

gem 'byebug'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'

group :development do
  gem 'bibtex-ruby'
  gem 'citeproc'
  gem 'csl-styles'
end
