# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2'

# The OpenSearch Ruby client allows you to interact with your OpenSearch clusters through Ruby methods
# rather than HTTP methods and raw JSON. https://opensearch.org/docs/latest/clients/ruby/
gem 'opensearch-ruby'

# UC3 Managed Gems
gem 'uc3-dmp-cloudwatch'
gem 'uc3-dmp-id'
