# We need to override the default us-west-2 region here for CloudFront which must reside in us-east-1
region: 'us-east-1'

# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
sceptre_user_data:
  env: 'stg'
  domain: 'dmphub.uc3stg.cdlib.net'
  hosted_zone: !ssm /uc3/dmp/hub/stg/HostedZoneId
  ssm_path: '/uc3/dmp/hub/stg/'
