# frozen_string_literal: true

source 'https://rubygems.org'

# No need to include any AWS SDK gems here since the Lambda functions have access
# to them by default
gem 'activerecord'
gem 'httparty'
gem 'json-schema'
gem 'mysql2'
gem 'rake'

# This is required to sign events published to EventBridge. The aws-crt is not automatically
# available to the Lambdas so we install here in the layer
# gem 'aws-sigv4', '1.4.1.crt'

group :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'aws-sdk-cognitoidentityprovider'
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-eventbridge'
  # gem 'aws-sdk-s3'
  gem 'aws-sdk-sns'
  gem 'aws-sdk-ssm'
end
