template:
  path: dynamo.yaml
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  Domain: !stack_attr sceptre_user_data.domain

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  # Dynamo settings
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  DynamoTableClass: 'STANDARD'
  DynamoEnableContributorInsights: 'true'
  DynamoEnablePointInTimeRecovery: 'false'
  DynamoBillingMode: 'PAY_PER_REQUEST'
  DynamoReadCapacityUnits: '16'
  DynamoWriteCapacityUnits: '60'

hooks:
  after_create:
    # Add Provenance items to the Dynamo Table
    - !cmd './seed_dynamo.sh prd DMPTool dmptool.org'
    - !cmd './seed_dynamo.sh prd DMPHub dmphub.uc3prd.cdlib.net'

    # Once the Dynamo table has been created, we can deploy our Lambdas and
    # the API Gateway which are managed by AWS SAM.
    #     Args are: environment, domain, build the Lambda layer (boolean)
    - !cmd 'cd ./src/sam && ruby sam_build_deploy.rb prd true true info'

    # Build and deploy the React based DMP ID Landing Page to the CloudFront S3 bucket
    # Args are: environment
    - !cmd 'cd ./src/landing_page && ruby build_deply.rb prd'
