# DMPTool Sceptre config
project_code: 'dmp'

region: 'us-west-2'

# In the cdl-uc3-prd account devs must call cloudformation using a service role
cloudformation_service_role:  !ssm
  name: /uc3/prd/CfnServiceRoleArn
  region: us-west-2
