# We need to override the default us-west-2 region here for CloudFront which must reside in us-east-1
region: 'us-east-1'

# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
sceptre_user_data:
  env: 'prd'
  domain: 'dmphub.uc3prd.cdlib.net'
  hosted_zone: !ssm
    name: /uc3/dmp/hub/prd/HostedZoneId
    region: us-west-2
  ssm_path: '/uc3/dmp/hub/prd/'
