template:
  path: 'initialize-db-pipeline.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !ssm /uc3/CodeStarConnectionArn

  S3ArtifactBucketId: !stack_output tool/s3.yaml::S3PrivateBucketId

  CodeBuildProjectName: !stack_output tool/dev/backend/codebuild.yaml::CodeBuildProjectId

  RepositoryName: 'CDLUC3/dmsp_backend_prototype'
  BranchToMonitor: 'chore/aws-reorg'
  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'