AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Application load balancer listener rules for the DMPTool ALB'

Parameters:

  CertificateArn:
    Type: 'String'

  AlbArn:
    Type: 'String'

  AlbTargetGroupArn:
    Type: 'String'

Resources:
  AlbListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref AlbArn
      DefaultActions:
        - Type: 'forward'
          TargetGroupArn: !Ref AlbTargetGroupArn
      Protocol: 'HTTP'
      Port: 80

  # Doesn't like the Cert below. I think we need to get the dmptool-dev.cdlib.org hosted zone setup

  # Listener that redirects all HTTP traffic to HTTPS
  # AlbListenerHttp:
  #   Type: 'AWS::ElasticLoadBalancingV2::Listener'
  #   Properties:
  #     LoadBalancerArn: !Ref AlbArn
  #     DefaultActions:
  #       - Type: 'redirect'
  #         RedirectConfig:
  #           Protocol: 'HTTPS'
  #           Port: 443
  #           Host: '#{host}'
  #           Path: '/#{path}'
  #           Query: '#{query}'
  #           StatusCode: 'HTTP_301'
  #     Protocol: 'HTTP'
  #     Port: 80

  # HTTPS Listener that sends traffic to the ALB
  # AlbListenerHttps:
  #   Type: 'AWS::ElasticLoadBalancingV2::Listener'
  #   Properties:
  #     LoadBalancerArn: !Ref AlbArn
  #     DefaultActions:
  #       - Type: 'forward'
  #         TargetGroupArn: !Ref AlbTargetGroupArn
  #     Protocol: 'HTTPS'
  #     Port: 443
  #     Certificates:
  #       - CertificateArn: !Ref CertificateArn

Outputs:
  AlbListenerId:
    Value: !Ref AlbListener

  # HttpListenerId:
  #   Value: !Ref AlbListenerHttp

  # HttpsListenerId:
  #   Value: !Ref AlbListenerHttps
