AWSTemplateFormatVersion: '2010-09-09'

Description: 'API Gateway uses a single IAM role for permissions for ALL APIs! Create one here and protect it from deletion.'

Resources:
  ApiCloudwatchRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: 'Retain'
    Properties:
      RoleName: !Sub 'Uc3ApiCloudwatchRole'
      Description: !Sub '${AWS::StackName} allows API Gateway to write access logs to Cloudwatch'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Principal:
            Service: 'apigateway.amazonaws.com'
          Effect: 'Allow'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

Outputs:
  ApiCloudwatchRoleArn:
    Value: !GetAtt ApiCloudwatchRole.Arn
    Export:
      Name: ApiCloudwatchRoleArn
