AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Final mappings/listeners that tie DNS traffic to resources'

Parameters:
  AlbArn:
    Type: 'String'

  AlbTargetGroupArn:
    Type: 'String'

  CertificateArn:
    Type: 'String'

  WafArn:
    Type: 'String'

Resources:

  # AlbListenerHttp:
  #   Type: 'AWS::ElasticLoadBalancingV2::Listener'
  #   Properties:
  #     LoadBalancerArn: !Ref AlbArn
  #     DefaultActions:
  #       - Type: 'forward'
  #         TargetGroupArn: !Ref AlbTargetGroupArn
  #     Protocol: 'HTTP'
  #     Port: 80

  # Listener that redirects all HTTP traffic to HTTPS
  AlbListenerHttp:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref AlbArn
      DefaultActions:
        - Type: 'redirect'
          RedirectConfig:
            Protocol: 'HTTPS'
            Port: 443
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: 'HTTP_301'
      Protocol: 'HTTP'
      Port: 80

  # HTTPS Listener that sends traffic to the ALB
  AlbListenerHttps:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref AlbArn
      DefaultActions:
        - Type: 'forward'
          TargetGroupArn: !Ref AlbTargetGroupArn
      Protocol: 'HTTPS'
      Port: 443
      Certificates:
        - CertificateArn: !Ref CertificateArn

  WafAlbAssociation:
    Type: 'AWS::WAFv2::WebACLAssociation'
    Properties:
      WebACLArn: !Ref WafArn
      ResourceArn: !Ref AlbArn

Outputs:

  HttpListenerId:
    Value: !Ref AlbListenerHttp
  HttpsPListenerId:
    Value: !Ref AlbListenerHttps