AWSTemplateFormatVersion: '2010-09-09'

Description: 'SSL Cert for all DMPHub endpoints'

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  HostedZoneId:
    Type: 'String'

  Domain:
    Type: 'String'

Resources:
  # --------------------------------------------------------------------------
  # SSL Certs (we likely only need one to protect the Alb, Api and Cognito, but since
  # we're using a hosted zone we need separate ones :/)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html
  # --------------------------------------------------------------------------
  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub "*.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "*.${Domain}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: 'DNS'
      SubjectAlternativeNames:
        - !Ref Domain

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub '${Env}-CertificateArn'
