AWSTemplateFormatVersion: '2010-09-09'

Description: 'Cloud9 Bastion/Jump box used to access RDS and run DB migrations'

Parameters:
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'

  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  IdleTimeoutMinutes:
    Type: 'Number'
    Default: 15

  ImageId:
    Type: 'String'
    Default: 'amazonlinux-2023-x86_64'

  InstanceType:
    Type: 'String'
    Default: 't2.micro'

  Program:
    Type: 'String'

  Service:
    Type: 'String'

  Subservice:
    Type: 'String'

  Environment:
    Type: 'String'

  CodeRepo:
    Type: 'String'

  Contact:
    Type: 'String'

Resources:
  # -----------------------------------------------------------
  # Cloud9
  #  See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html
  # -----------------------------------------------------------
  Bastion:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      AutomaticStopTimeMinutes: !Ref IdleTimeoutMinutes
      ConnectionType: 'CONNECT_SSM'
      Description: !Sub "${AWS::StackName} Bastion to provide access to RDS"
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      # Name: !Sub "${Program}-${Service}-${Subservice}-${Environment}-bastion"
      SubnetId: !Ref SubnetId
      Tags:
        - Key: 'Program'
          Value: !Ref Program
        - Key: 'Service'
          Value: !Ref Service
        - Key: 'Subservice'
          Value: !Ref Subservice
        - Key: 'Environment'
          Value: !Ref Environment
        - Key: 'CodeRepo'
          Value: !Ref CodeRepo
        - Key: 'Contact'
          Value: !Ref Contact
        - Key: 'ConfigExclude'
          Value: 'Security-group-attached-to-ENI'

Outputs:
  BastionId:
    Value: !Ref Bastion

  BastionArn:
    Value: !GetAtt Bastion.Arn

  BastionName:
    Value: !GetAtt Bastion.Name
