AWSTemplateFormatVersion: '2010-09-09'

Description: 'Cognito user pool app integration'

Parameters:
  UserPoolId:
    Type: 'String'

  Env:
    Type: 'String'
    Default: 'dev'

  Domain:
    Type: 'String'

  Subdomain:
    Type: 'String'

  ClientName:
    Type: 'String'

  ClientCallbackUri:
    Type: 'String'

  Scopes:
    Type: 'List<String>'

  OnlyAllowAdminsToCreateUsers:
    Type: 'String'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  UnusedAccountValidityDays:
    Type: 'Number'
    Default: 14

  MinimumPasswordLength:
    Type: 'Number'
    Default: 8

  TokenValidityUnits:
    Type: 'String'
    Default: 'minutes'
    AllowedValues:
      - 'seconds'
      - 'minutes'
      - 'hours'
      - 'days'

  AccessTokenValidity:
    Type: 'Number'
    Default: 10

  AuthSessionValidatyMinutes:
    Type: 'Number'
    Default: 3

  IdTokenValidity:
    Type: 'Number'
    Default: 7

  RefreshTokenValidity:
    Type: 'Number'
    Default: 10080 # 7 days

Resources:
  # --------------------------------------------------------------
  # Cognito UserPool application clients
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html
  # --------------------------------------------------------------
  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    DeletionPolicy: Retain
    Properties:
      ClientName: !Ref ClientName
      UserPoolId: !Ref UserPoolId
      ExplicitAuthFlows:
        - 'ALLOW_ADMIN_USER_PASSWORD_AUTH'
        - 'ALLOW_CUSTOM_AUTH'
        - 'ALLOW_USER_SRP_AUTH'
        - 'ALLOW_REFRESH_TOKEN_AUTH'
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - 'client_credentials'
      AllowedOAuthScopes: !Ref Scopes
      EnableTokenRevocation: true
      PreventUserExistenceErrors: 'ENABLED'
      GenerateSecret: true
      SupportedIdentityProviders:
        - 'COGNITO'
      # The CF docs indicate that this is not required but I am unable to get a token from Cognito without it
      CallbackURLs:
        - !Ref ClientCallbackUri
      TokenValidityUnits:
        AccessToken: !Ref TokenValidityUnits
        IdToken: !Ref TokenValidityUnits
        RefreshToken: !Ref TokenValidityUnits
      # The token issued after the user signs in
      AccessTokenValidity: !Ref AccessTokenValidity
      # The length (minutes) that a session token for each API request in an authentication flow lasts
      AuthSessionValidity: !Ref AuthSessionValidatyMinutes
      # The token used during user authentication
      IdTokenValidity: !Ref IdTokenValidity
      # The length of time the user can refresh their token
      RefreshTokenValidity: !Ref RefreshTokenValidity

Outputs:
  LogicalClientId:
    Value: !Ref UserPoolClient

  ClientId:
    Value: !GetAtt UserPoolClient.ClientId