AWSTemplateFormatVersion: '2010-09-09'

Description: 'DynamoDB that backs the API dmp-hub-sam'

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  Domain:
    Type: 'String'

  SsmPath:
    Type: 'String'

  DynamoTableClass:
    Type: 'String'
    Default: 'STANDARD'
    AllowedValues:
      - 'STANDARD'
      - 'STANDARD_INFREQUENT_ACCESS'
  DynamoEnableContributorInsights:
    Type: 'String'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  DynamoEnablePointInTimeRecovery:
    Type: 'String'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  DynamoBillingMode:
    Type: 'String'
    Default: 'PROVISIONED'
    AllowedValues:
      - 'PROVISIONED'
      - 'PAY_PER_REQUEST'
  DynamoReadCapacityUnits:
    Type: 'Number'
    Default: 10
  DynamoWriteCapacityUnits:
    Type: 'Number'
    Default: 10

  RdsSnapshot:
    Type: 'String'
    Default: 'none'

Conditions:
  PreventDelete:
    !Equals [!Ref Env, 'prd']

Resources:
  # ----------------------------------------------
  # DynamoDB polymorphic table
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  # ----------------------------------------------
  DynamoTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: !If
      - PreventDelete
      - 'Retain'
      - 'Delete'
    Properties:
      # The base table's Partition key and Sort Key define both the DMP ID and version
      # There are 3 potential variants of these keys:
      # PK - PROVENANCE#dmptool,      SK - PROFILE                       <--- Provenance info
      # PK - PROVENANCE#dmptool,      SK - DMPS                          <--- Array of DMP PKs for the Provenance
      # PK - DMP#doi:10.48321/D1M30K, SK - VERSION#latest                <--- Latest version
      # PK - DMP#doi:10.48321/D1M30K, SK - VERSION#2022-02-18T12:30:25Z  <--- Historical version
      # PK - PERSON#[orcid],          SK - DMPS                          <--- Array of DMP PKs for the Person
      # PK - AFFILIATION#[id],        SK - DMPS                          <--- Array of DMP PKs for the Affiliation / Funder
      # PK - RELATED#[:id],           SK - DMPS                          <--- Array of DMP PKs for the Related Identifier / Grant

      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'

      AttributeDefinitions:
        # DMPHub attribute that stores the provenance/DMP id (see above)
        - AttributeName: 'PK'
          AttributeType: 'S'
        # DMPHub attribute that stores the provenance profile or the DMP version (see above)
        - AttributeName: 'SK'
          AttributeType: 'S'
        # DMPHub attribute that stores the mod date as YYYY-MM-DD for fast date range retrievals
        - AttributeName: 'dmphub_modification_day'
          AttributeType: 'S'
        # DMPHub attribute that stores the ORCID id of the contact
        - AttributeName: 'dmphub_owner_id'
          AttributeType: 'S'
        # DMPHub attribute that stores the ROR id of the contact
        - AttributeName: 'dmphub_owner_org'
          AttributeType: 'S'
        # The originating provenance system's ID for the DMP
        - AttributeName: 'dmphub_provenance_identifier'
          AttributeType: 'S'
        # The featured flag
        - AttributeName: 'dmproadmap_featured'
          AttributeType: 'N'

      GlobalSecondaryIndexes:
        # An index to help us quickly fetch all of the DMPs for a specific date range
        - IndexName: 'dmphub_modification_day_gsi'
          KeySchema:
            - AttributeName: 'dmphub_modification_day'
              KeyType: 'HASH'
            - AttributeName: 'PK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes: ['SK', 'title', 'description', 'created', 'modified', 'contact', 'contributor', 'project', 'dmproadmap_assertion_needed']
          ContributorInsightsSpecification:
            Enabled: !Ref DynamoEnableContributorInsights
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoWriteCapacityUnits

        # An index to help us quickly fetch all of the DMPs for a specific organization
        - IndexName: 'dmphub_owner_id_gsi'
          KeySchema:
            - AttributeName: 'dmphub_owner_id'
              KeyType: 'HASH'
            - AttributeName: 'PK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes: ['SK', 'title', 'description', 'created', 'modified', 'contact', 'contributor', 'project', 'dmproadmap_assertion_needed']
          ContributorInsightsSpecification:
            Enabled: !Ref DynamoEnableContributorInsights
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoWriteCapacityUnits

        # An index to help us quickly fetch all of the DMPs for a specific organization
        - IndexName: 'dmphub_owner_org_gsi'
          KeySchema:
            - AttributeName: 'dmphub_owner_org'
              KeyType: 'HASH'
            - AttributeName: 'PK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes: ['SK', 'title', 'description', 'created', 'modified', 'contact', 'contributor', 'project', 'dmproadmap_assertion_needed']
          ContributorInsightsSpecification:
            Enabled: !Ref DynamoEnableContributorInsights
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoWriteCapacityUnits

        # An index to help us quickly fetch a DMP by its identifier for the provenance system
        - IndexName: 'dmphub_provenance_identifier_gsi'
          KeySchema:
            - AttributeName: 'dmphub_provenance_identifier'
              KeyType: 'HASH'
            - AttributeName: 'dmphub_modification_day'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes: ['PK', 'SK', 'title']
          ContributorInsightsSpecification:
            Enabled: !Ref DynamoEnableContributorInsights
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoWriteCapacityUnits

        # An index to help us quickly fetch the DMP IDs that have been 'featured'
        - IndexName: 'dmproadmap_featured_gsi'
          KeySchema:
            - AttributeName: 'dmproadmap_featured'
              KeyType: 'HASH'
            - AttributeName: 'SK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes: ['PK', 'SK', 'title', 'description', 'created', 'modified', 'contact', 'contributor', 'project', 'dmproadmap_assertion_needed']
          ContributorInsightsSpecification:
            Enabled: !Ref DynamoEnableContributorInsights
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoWriteCapacityUnits

      BillingMode: !Ref DynamoBillingMode
      TableClass: !Ref DynamoTableClass
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoReadCapacityUnits
        WriteCapacityUnits: !Ref DynamoWriteCapacityUnits
      ContributorInsightsSpecification:
        Enabled: !Ref DynamoEnableContributorInsights
      # Determine cost before enabling
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref DynamoEnablePointInTimeRecovery

  # ----------------------------------------------
  # SSM Parameter Store
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
  # ----------------------------------------------
  BaseUrlParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} Domain"
      Name: !Sub "${SsmPath}BaseUrl"
      Type: 'String'
      Value: !Sub "https://${Domain}"

  TableNameParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} DynamoDb Table"
      Name: !Sub "${SsmPath}DynamoTableName"
      Type: 'String'
      Value: !Select [1, !Split ['/', !GetAtt DynamoTable.Arn]]

Outputs:
  DynamoTableName:
    Value: !Select [1, !Split ['/', !GetAtt DynamoTable.Arn]]
    Export:
      Name: !Sub '${Env}-DynamoTableName'

  DynamoTableId:
    Value: !Ref DynamoTable

  DynamoTableArn:
    Value: !GetAtt DynamoTable.Arn
    Export:
      Name: !Sub '${Env}-DynamoTableArn'