AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Elastic container registry for DMPTool build images'

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  ECRLifecyclePolicyTagPrefix:
    Type: 'String'

Resources:
  # -----------------------------------------------------------
  # Elastic Container Repository (ECR) - Hosts the application's Docker images
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECR.html
  # -----------------------------------------------------------
  EcrRepository:
    Type: 'AWS::ECR::Repository'
    DeletionPolicy: 'Retain'
    Properties:
      RepositoryName: !Ref AWS::StackName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        # TODO: Update this to only keep the last 3 snapshots of 'untagged' since we
        #       are using 'latest' as the only tag.
        LifecyclePolicyText: !Sub >
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 1,
                  "tagStatus": "tagged",
                  "tagPrefixList": [
                    "${ECRLifecyclePolicyTagPrefix}"
                  ]
                },
                "description": "Ensure that we do not have more than 1 tagged version",
                "rulePriority": 1
              },
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 3,
                  "tagStatus": "untagged"
                },
                "description": "Only retain the last 3 versions",
                "rulePriority": 2
              }
            ]
          }

Outputs:
  EcrRepositoryName:
    Value: !Ref EcrRepository

  EcrRepositoryARN:
    Value: !GetAtt EcrRepository.Arn

  EcrRepositoryURI:
    Value: !GetAtt EcrRepository.RepositoryUri