AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Build for our ECR'

Parameters:
  SsmPath:
    Type: 'String'

  EcrLifecyclePolicyTagPrefix:
    Type: 'String'
    Default: 'latest'

Resources:
  # -----------------------------------------------------------
  # Elastic Container Repository (ECR) - Hosts the Rails application's Docker images
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECR.html
  # -----------------------------------------------------------
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub '${AWS::StackName}-ecr'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: !Sub >
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 1,
                  "tagStatus": "tagged",
                  "tagPrefixList": [
                    "${EcrLifecyclePolicyTagPrefix}"
                  ]
                },
                "description": "Ensure that we do not have more than 1 tagged version",
                "rulePriority": 1
              },
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 3,
                  "tagStatus": "untagged"
                },
                "description": "Only retain the last 3 versions",
                "rulePriority": 2
              }
            ]
          }

  # Add the ECR URI to SSM
  EcrUriParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} ECR URI"
      Name: !Sub "${SsmPath}EcrUri"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt ECRRepository.RepositoryUri

  EcrNameParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} ECR Name"
      Name: !Sub "${SsmPath}EcrName"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !Ref AWS::StackName

Outputs:
  EcrRepositoryName:
    Value: !Ref ECRRepository
  EcrRepositoryArn:
    Value: !GetAtt ECRRepository.Arn
  EcrRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
