AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Serverless architecture for the DMPTool system'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  Env:
    Type: 'String'
    Default: 'dev'

  AppName:
    Type: 'String'

  EcsDesiredServiceCount:
    Type: 'Number'
    Default: 1

  EcrRepositoryUri:
    Type: 'String'

  AlbTargetGroupArn:
    Type: 'String'

  AlbSecurityGroupId:
    Type: 'String'

  DynamoTableName:
    Type: 'String'

  HelpdeskEmail:
    Type: 'String'

Conditions:
  IsDev:
    !Equals [!Ref Env, 'dev']

Resources:
  # -----------------------------------------------------------
  # Identitity and Access Management (IAM)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_IAM.html
  # -----------------------------------------------------------
  # Role that grants the ECS container agent permission to make AWS API calls
  EcsTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'

  # Role that grants containers in the task permission to call AWS APIs on your behalf
  EcsTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'

  # -----------------------------------------------------------
  # EC2 Security Groups for ECS containers (see their definitions in application.yaml)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  # -----------------------------------------------------------
  EcsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'Fargate security group for ${AWS::StackName}'
      GroupName: !Sub '${AWS::StackName}-ecs-sec'
      VpcId: !Ref VpcId

  # Allow traffic to the ECS instances from the ALB
  EcsSecurityGroupIngressFromAlb:
    Type: 'AWS::EC2::SecurityGroupIngress'
    DependsOn:
      - EcsSecurityGroup
    Properties:
      IpProtocol: 'tcp'
      FromPort: 3000
      ToPort: 3000
      GroupId: !GetAtt EcsSecurityGroup.GroupId
      SourceSecurityGroupId: !Ref AlbSecurityGroupId

  # -----------------------------------------------------------
  # Elastic Container Service (ECS) - Containers that host the application
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECS.html
  # -----------------------------------------------------------
  EcsCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub '${AWS::StackName}-fargate-clst'
      CapacityProviders:
        - 'FARGATE'
      DefaultCapacityProviderStrategy:
        - CapacityProvider: 'FARGATE'

  # The Application/Task definition
  EcsTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - EcsTaskExecutionRole
      - EcsTaskRole
    Properties:
      Cpu: '2048' # 2 vCPU
      Memory: '4096' # 4GB
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt EcsTaskRole.Arn
      Family: !Sub '${AWS::StackName}-fargate'
      NetworkMode: 'awsvpc' # Required for Fargate!
      RuntimePlatform:
        CpuArchitecture: 'X86_64'
        OperatingSystemFamily: 'LINUX'
      RequiresCompatibilities:
        - 'FARGATE'
      ContainerDefinitions:
        -
          Image: !Ref EcrRepositoryUri
          Cpu: 2
          DisableNetworking: false
          Essential: true
          Interactive: true
          Memory: 2000
          Name: !Ref AppName
          StartTimeout: 30
          StopTimeout: 30
          # TODO: Figure out what container health check should be run (e.g. memory usage)
          # HealthCheck:
          #   Command:  ["CMD-SHELL", "echo hello"]
          #   Interval: 5
          #   Retries: 2
          #   Timeout: 3
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-create-group: true
              awslogs-group: !Ref AWS::StackName
              awslogs-stream-prefix: !Ref AppName
          PortMappings:
            # SES port
            - ContainerPort: 25
              Protocol: 'tcp'
            # ALB port
            - ContainerPort: 4000
              Protocol: 'tcp'
          Environment:
            - Name: 'DMSP_TABLE'
              Value: !Ref DynamoTableName
            - Name: 'HELPDESK_EMAIL'
              Value: !Ref HelpdeskEmail

  # Container Service definition
  EcsService:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - EcsTaskDefinition
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref EcsDesiredServiceCount
      EnableECSManagedTags: true
      HealthCheckGracePeriodSeconds: 180
      LaunchType: 'FARGATE'
      DeploymentConfiguration:
        MinimumHealthPercent: 100
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        # If this is dev then just do a rolling deploy, otherwise use the blue/green strategy
        Type: !If
          - IsDev
          - 'ECS'
          - 'CODE_DEPLOY'
      LoadBalancers:
        - TargetGroupArn: !Ref AlbTargetGroupArn
          ContainerPort: 4000
          ContainerName: !Ref AppName
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !GetAtt EcsSecurityGroup.GroupId
            - !Ref AlbSecurityGroupId
          AssignPublicIp: 'ENABLED'
          Subnets: !Ref Subnets
      PlatformVersion: 'LATEST'
      PropagateTags: 'TASK_DEFINITION'
      SchedulingStrategy: 'REPLICA'
      TaskDefinition: !Ref EcsTaskDefinition

Outputs:
  EcsFargateClusterId:
    Value: !Ref EcsCluster

  EcsFargateClusterArn:
    Value: !GetAtt EcsCluster.Arn

  EcsServiceArn:
    Value: !Ref EcsService

  EcsServiceName:
    Value: !GetAtt EcsService.Name

  EcsTaskId:
    Value: !Ref EcsTaskDefinition
