AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda Layer for the DMPHub

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  NameSuffix:
    Type: 'String'

  S3Bucket:
    Type: 'String'

  S3KeyPrefix:
    Type: 'String'

  CompatibleRuntime:
    Type: 'String'
    AllowedValues:
      - 'ruby2.7'
      - 'ruby3.2'

  CompatibleArchitecture:
    Type: 'String'
    Default: 'x86_64'
    AllowedValues:
      - 'x86_64'
      - 'arm64'

Resources:
  # ----------------------------------------------------
  # Lambda Layers
  #   See: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html
  # ----------------------------------------------------
  LambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      LayerName: !Sub '${AWS::StackName}-${NameSuffix}'
      Description: 'Lambda Layer for use with Lambdas triggered by ${NameSuffix} requests'
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub '${S3KeyPrefix}${Env}-${NameSuffix}.zip'
      CompatibleArchitectures:
        - !Ref CompatibleArchitecture
      CompatibleRuntimes:
        - !Ref CompatibleRuntime

Outputs:
  LambdaLayerVersionId:
    Value: !Ref LambdaLayer

  LambdaLayerVersionArn:
    Value: !GetAtt LambdaLayer.LayerVersionArn
