AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Builds for LogGroup, EC2 Security Group, Dynamo table, S3, SQS and SNS resources'

Parameters:
  LogRetentionDays:
    Type: 'Number'
    Default: 7

Resources:
  # ----------------------------------------------
  # Catchall CloudWatch LogGroup
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Logs.html
  #
  # Generic LogGroup to dump logs to
  # ----------------------------------------------
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref LogRetentionDays

  # ----------------------------------------------
  # Simple Storage Service (S3) buckets
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  #
  # S3 Bucket to store logs from services like CloudFront (not publicly accessible)
  # ----------------------------------------------
  S3LogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true

Outputs:
  LogGroupId:
    Value: !Ref LogGroup
  LogGroupArn:
    Value: !GetAtt LogGroup.Arn

  S3LogBucketId:
    Value: !Ref S3LogBucket
