AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Code build and pipeline for the a Pipeline to watch a DMP system codebase'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  CodeStarConnectionArn:
    Type: 'String'

  Env:
    Type: 'String'
    Default: 'dev'

  LogRetentionDays:
    Type: 'Number'
    Default: 7

  ProgramTag:
    Type: 'String'

  ServiceTag:
    Type: 'String'

  SubserviceTag:
    Type: 'String'

  CodeRepoTag:
    Type: 'String'

  ContactTag:
    Type: 'String'

Resources:


Outputs:
  IamPipelineRoleArn:
    Value: !GetAtt IamPipelineRole.Arn

  PipelineLogGroupName:
    Value: !Ref PipelineLogGroup

  PipelineLogGroupArn:
    Value: !GetAtt PipelineLogGroup.Arn

  PipelineSecurityGroupId:
    Value: !Ref CodeBuildSecurityGroup
