AWSTemplateFormatVersion: '2010-09-09'

Description: 'Code build and pipeline for the a Pipeline to watch a DMP system codebase'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  CodeStarConnectionArn:
    Type: 'String'

  S3CloudFrontBucketId:
    Type: 'String'
  CloudFrontDistroId:
    Type: 'String'

  S3ArtifactBucketId:
    Type: 'String'
  S3LogBucketId:
    Type: 'String'

  CodeBuildEmail:
    Type: 'String'
  SnsTopicEmailArn:
    Type: 'String'

  CodeBuildSecurityGroupId:
    Type: 'String'
  IamPipelineRoleArn:
    Type: 'String'
  PipelineLogGroupName:
    Type: 'String'
  PipelineLogGroupArn:
    Type: 'String'

  CodeBuildEnvironmentType:
    Type: 'String'
    Default: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType:
    Type: 'String'
    Default: 'BUILD_GENERAL1_SMALL'
  CodeBuildEnvironmentImage:
    Type: 'String'
    Default: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
  CodeBuildArtifactType:
    Type: 'String'
    Default: 'CODEPIPELINE'
  CodeBuildTimeout:
    Type: 'Number'
    Default: 15 # minutes

  CodePipelineRestartExecutionOnUpdate:
    Type: 'String'
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  CodePipelineDeploymentTimeout:
    Type: 'String'
    Default: '15'
  CodePipelineBuildArtifactFileName:
    Type: 'String'
    Default: 'imagedefinitions.json'

  RepositoryName:
    Type: 'String'
  BranchToMonitor:
    Type: 'String'
    Default: 'main'
  SourceOutputArtifactFormat:
    Type: 'String'
    Default: 'CODEBUILD_CLONE_REF'

Resources:
  # -----------------------------------------------------------
  # Identitity and Access Management (IAM)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_IAM.html
  # -----------------------------------------------------------
  IamCodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-build-policy'
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                    "logs:AssociateKmsKey"
                  ],
                  "Resource": [
                    "${PipelineLogGroupArn}"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "cloudwatch:PutMetricData"
                  ],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:*",
                    "ec2:CreateNetworkInterface",
                    "ec2:DescribeNetworkInterfaces",
                    "ec2:DeleteNetworkInterface",
                    "ec2:DescribeSubnets",
                    "ec2:DescribeSecurityGroups",
                    "ec2:DescribeDhcpOptions",
                    "ec2:DescribeVpcs",
                    "ec2:CreateNetworkInterfacePermission"
                  ],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": ["codestar-connections:UseConnection"],
                  "Resource": "${CodeStarConnectionArn}"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "cloudfront:UpdateDistribution",
                    "cloudfront:DeleteDistribution",
                    "cloudfront:CreateInvalidation"
                  ],
                  "Resource": "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistroId}"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "sns:Publish"
                  ],
                  "Resource": "${SnsTopicEmailArn}"
                }
              ]
            }

  # -----------------------------------------------------------
  # CodeBuild
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
  # -----------------------------------------------------------
  DmpHubCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      ServiceRole: !GetAtt IamCodeBuildRole.Arn
      Artifacts:
        Type: !Ref CodeBuildArtifactType
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref PipelineLogGroupName
          Status: 'ENABLED'
          StreamName: 'codebuild'
      Environment:
        Type: !Ref CodeBuildEnvironmentType
        ComputeType: !Ref CodeBuildEnvironmentComputeType
        Image: !Ref CodeBuildEnvironmentImage
        # This is required in order for the Docker daemon to work!
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: 'S3_BUCKET'
            Value: !Ref S3CloudFrontBucketId
          - Name: 'CLOUDFRONT_DISTRO_ID'
            Value: !Ref CloudFrontDistroId
          - Name: 'SNS_EMAIL_TOPIC'
            Value: !Ref SnsTopicEmailArn
      Source:
        Type: !Ref CodeBuildArtifactType
      TimeoutInMinutes: !Ref CodeBuildTimeout
      VpcConfig:
        VpcId: !Ref VpcId
        Subnets: !Ref Subnets
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroupId
      Cache:
        Type: 'S3'
        Location: !Sub '${S3ArtifactBucketId}/dmphub/build-cache'

  # -----------------------------------------------------------
  # CodePipeline
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  # -----------------------------------------------------------
  DmpHubPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref S3ArtifactBucketId
        # CloudFormation only supports S3 at the moment!
        Type: 'S3'
      RestartExecutionOnUpdate: !Ref CodePipelineRestartExecutionOnUpdate
      RoleArn: !Ref IamPipelineRoleArn
      Stages:
        - Name: 'MonitorRepo'
          Actions:
            # This action is triggered when the development branch of DMPRoadmap has a new commit
            # it's output is the commit hash
            - Name: 'DmpHubUi'
              RunOrder: 1
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Provider: 'CodeStarSourceConnection'
                Version: '1'
              # See: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html
              # for info on tying CodeBuild in
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref RepositoryName
                BranchName: !Ref BranchToMonitor
                OutputArtifactFormat: !Ref SourceOutputArtifactFormat
              OutputArtifacts:
                - Name: !Sub "dmphub-code"

        - Name: 'DockerBuildPublish'
          Actions:
            # This action is triggered by either the DMPRoadmapPush or DockerPush actions. This
            # action uses the DMPRoadmapPush commit hash to the latest DockerPush zip to build
            # the Docker image
            - Name: 'DmpHubBuildDeploy'
              RunOrder: 2
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              # RoleArn: !GetAtt IamCodeBuildRole.Arn
              Configuration:
                ProjectName: !Ref DmpHubCodeBuildProject
                PrimarySource: !Sub "dmphub-code"
              InputArtifacts:
                - Name: !Sub "dmphub-code"
              OutputArtifacts:
                - Name: !Sub "dmphub-build"

Outputs:
  CodeBuildRoleId:
    Value: !Ref IamCodeBuildRole
  CodeBuildRoleArn:
    Value: !GetAtt IamCodeBuildRole.Arn

  DmpHubCodeBuildProjectName:
    Value: !Ref DmpHubCodeBuildProject
  DmpHubCodeBuildProjectArn:
    Value: !GetAtt DmpHubCodeBuildProject.Arn

  DmpHubPipelineId:
    Value: !Ref DmpHubPipeline
  DmpHubPipelineVersion:
    Value: !GetAtt DmpHubPipeline.Version
