AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Code build and pipeline for the a Pipeline to watch a DMP system codebase'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  CodeStarConnectionArn:
    Type: 'String'

  EcrRepositoryUri:
    Type: String

  EcrRepositoryName:
    Type: String

  S3ArtifactBucketId:
    Type: 'String'

  AlbTargetGroupFullName:
    Type: 'String'

  # EcsClusterName:
  #   Type: 'String'

  # EcsServiceName:
  #   Type: 'String'

  CodeBuildSecurityGroupId:
    Type: 'String'

  IamPipelineRoleArn:
    Type: 'String'

  PipelineLogGroupName:
    Type: 'String'

  PipelineLogGroupArn:
    Type: 'String'

  SsmPath:
    Type: 'String'

  CodeBuildEnvironmentType:
    Type: 'String'
    Default: 'LINUX_CONTAINER'

  CodeBuildEnvironmentComputeType:
    Type: 'String'
    Default: 'BUILD_GENERAL1_SMALL'

  CodeBuildEnvironmentImage:
    Type: 'String'
    Default: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'

  CodeBuildArtifactType:
    Type: 'String'
    Default: 'CODEPIPELINE'

  CodeBuildTimeout:
    Type: 'Number'
    Default: 15 # minutes

  RepositoryName:
    Type: 'String'

  BranchToMonitor:
    Type: 'String'
    Default: 'main'

  SourceOutputArtifactFormat:
    Type: 'String'
    Default: 'CODEBUILD_CLONE_REF'

Resources:
  # -----------------------------------------------------------
  # Identitity and Access Management (IAM)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_IAM.html
  # -----------------------------------------------------------
  IamCodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-build-policy'
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                    "logs:AssociateKmsKey"
                  ],
                  "Resource": [
                    "${PipelineLogGroupArn}"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "cloudwatch:PutMetricData"
                  ],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:*",
                    "ec2:CreateNetworkInterface",
                    "ec2:DescribeNetworkInterfaces",
                    "ec2:DeleteNetworkInterface",
                    "ec2:DescribeSubnets",
                    "ec2:DescribeSecurityGroups",
                    "ec2:DescribeDhcpOptions",
                    "ec2:DescribeVpcs",
                    "ec2:CreateNetworkInterfacePermission"
                  ],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": ["codestar-connections:UseConnection"],
                  "Resource": "${CodeStarConnectionArn}"
                },
                {
                  "Effect": "Allow",
                  "Action": ["ssm:GetParameters"],
                  "Resource": ["*"]
                }
              ]
            }

  IamCodeDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codedeploy.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS'

  # -----------------------------------------------------------
  # CodeBuild
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_CodeBuild.html
  # -----------------------------------------------------------
  DmpToolCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      ServiceRole: !GetAtt IamCodeBuildRole.Arn
      Artifacts:
        Type: !Ref CodeBuildArtifactType
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref PipelineLogGroupName
          Status: 'ENABLED'
          StreamName: 'codebuild'
      Environment:
        Type: !Ref CodeBuildEnvironmentType
        ComputeType: !Ref CodeBuildEnvironmentComputeType
        Image: !Ref CodeBuildEnvironmentImage
        # This is required in order for the Docker daemon to work!
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: 'ECR_REPOSITORY_URI'
            Value: !Ref EcrRepositoryUri

          - Name: 'ECR_REPOSITORY_NAME'
            Value: !Ref EcrRepositoryName

          - Name: 'CREDENTIALS_ENC'
            Type: 'PARAMETER_STORE'
            Value: !Sub "${SsmPath}RailsCredentials"
            # Value: !Ref RailsCredentialsEnc

      Source:
        Type: !Ref CodeBuildArtifactType
      TimeoutInMinutes: 15
      VpcConfig:
        VpcId: !Ref VpcId
        Subnets: !Ref Subnets
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroupId
      Cache:
        Type: 'S3'
        Location: !Sub '${S3ArtifactBucketId}/dmptool/build-cache'


  # -----------------------------------------------------------
  # CodePipeline
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  # -----------------------------------------------------------
  DmpToolPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref S3ArtifactBucketId
        # CloudFormation only supports S3 at the moment!
        Type: 'S3'
      RestartExecutionOnUpdate: true
      RoleArn: !Ref IamPipelineRoleArn
      Stages:
        - Name: 'MonitorRepos'
          Actions:
            - Name: 'DmpTool'
              RunOrder: 1
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Provider: 'CodeStarSourceConnection'
                Version: '1'
              # See: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html
              # for info on tying CodeBuild in
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref RepositoryName
                BranchName: !Ref BranchToMonitor
                OutputArtifactFormat: !Ref SourceOutputArtifactFormat
              OutputArtifacts:
                - Name: 'dmptool_commit'

        - Name: 'DockerBuild'
          Actions:
            - Name: 'Build'
              RunOrder: 2
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              Configuration:
                ProjectName: !Ref DmpToolCodeBuildProject
                PrimarySource: !Sub 'dmptool_commit'
              InputArtifacts:
                - Name: 'dmptool_commit'
              OutputArtifacts:
                - Name: 'dmptool_image'


Outputs:
  CodeBuildRoleId:
    Value: !Ref IamCodeBuildRole
  CodeBuildRoleArn:
    Value: !GetAtt IamCodeBuildRole.Arn

  CodeDeployRoleId:
    Value: !Ref IamCodeDeployRole
  CodeDeployRoleArn:
    Value: !GetAtt IamCodeDeployRole.Arn

  DmpToolCodeBuildProjectName:
    Value: !Ref DmpToolCodeBuildProject
  DmpToolCodeBuildProjectArn:
    Value: !GetAtt DmpToolCodeBuildProject.Arn



  DmpToolPipelineId:
    Value: !Ref DmpToolPipeline
  DmpToolPipelineVersion:
    Value: !GetAtt DmpToolPipeline.Version
