AWSTemplateFormatVersion: '2010-09-09'
Description: 'Redis Cache for the Apollo server'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  Env:
    Type: 'String'
    Default: 'dev'

  CachePort:
    Type: 'Number'
    Default: 6379

Resources:
  RedisCacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub "${AWS::StackName} Redis cache SecGrp"
      GroupName: !Sub "${AWS::StackName}-RedisSecGrp"
      VpcId: !Ref VpcId

  RedisCacheSecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt RedisCacheSecurityGroup.GroupId
      IpProtocol: 'tcp'
      FromPort: !Ref CachePort
      ToPort: !Ref CachePort
      SourceSecurityGroupId: !GetAtt RedisCacheSecurityGroup.GroupId

  RedisCache:
    Type: 'AWS::ElastiCache::ServerlessCache'
    Properties:
      Engine: 'redis'
      SecurityGroupIds:
        - !GetAtt RedisCacheSecurityGroup.GroupId
      ServerlessCacheName: !Sub "dmptool-${Env}-redis"
      SubnetIds: !Ref Subnets

Outputs:
  RedisCacheSecurityGroupID:
    Value: !GetAtt RedisCacheSecurityGroup.GroupId

  RedisName:
    Value: !Ref RedisCache

  RedisArn:
    Value: !GetAtt RedisCache.ARN

  RedisEngineVersion:
    Value: !GetAtt RedisCache.FullEngineVersion

  RedisCacheHost:
    Value: !GetAtt RedisCache.Endpoint.Address

  RedisCachePort:
    Value: !GetAtt RedisCache.Endpoint.Port

  RedisReaderHost:
    Value: !GetAtt RedisCache.ReaderEndpoint.Address

  RedisReaderPort:
    Value: !GetAtt RedisCache.ReaderEndpoint.Port
