AWSTemplateFormatVersion: '2010-09-09'

Description: 'DNS for the Fargate cluster, API and Cognito'

Parameters:
  HostedZoneId:
    Type: 'AWS::Route53::HostedZone::Id'

  Domain:
    Type: 'String'

  RecordType:
    Type: 'String'
    Default: 'A'

  # Defaults to the AWS Global region: us-east-1
  TargetRegion:
    Type: 'String'
    Default: 'us-east-1'

  TargetName:
    Type: 'String'

  TargetHostedZoneId:
    Type: 'String'

  SetIdentifier:
    Type: 'String'

Conditions:
  UseSetIdentifier:
    !Not [!Equals [!Ref SetIdentifier, 'none']]

Resources:
  # -----------------------------------------------------------
  # Route53 - DNS configuration
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Route53.html
  # -----------------------------------------------------------
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Domain
      Type: !Ref RecordType
      Region: !Ref TargetRegion
      SetIdentifier: !If
        - UseSetIdentifier
        - !Ref SetIdentifier
        - !Ref AWS::NoValue
      AliasTarget:
        DNSName: !Ref TargetName
        HostedZoneId: !Ref TargetHostedZoneId
        # EvaluateTargetHealth: true

Outputs:
  DomainName:
    Value: !Ref RecordSet
