AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'DNS for the Fargate cluster, API and Cognito'

Parameters:
  HostedZoneId:
    Type: 'AWS::Route53::HostedZone::Id'

  Domain:
    Type: 'String'

  RecordType:
    Type: 'String'
    Default: 'A'

  TargetName:
    Type: 'String'

  TargetHostedZoneId:
    Type: 'String'

Resources:
  # -----------------------------------------------------------
  # Route53 - DNS configuration
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Route53.html
  # -----------------------------------------------------------
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Domain
      Type: !Ref RecordType
      AliasTarget:
        DNSName: !Ref TargetName
        HostedZoneId: !Ref TargetHostedZoneId
        # EvaluateTargetHealth: true

Outputs:
  DomainName:
    Value: !Ref RecordSet
