AWSTemplateFormatVersion: '2010-09-09'

Description: 'S3 buckets both public (app files) and private (CodePipeline, CodeBuild, etc.)'

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  SsmPath:
    Type: 'String'

  LogBucketObjectLifeSpan:
    Type: 'Number'
    Default: 30

Conditions:
  PreventDelete:
    !Equals [!Ref Env, 'prd']

Resources:
  # ----------------------------------------------
  # Simple Storage Service (S3) buckets
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  # ----------------------------------------------
  # S3 Bucket to store logs from services like CloudFront
  S3LogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If
      - PreventDelete
      - 'Retain'
      - 'Delete'
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref LogBucketObjectLifeSpan
            Status: 'Enabled'
      AccessControl: 'Private'
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket that stores DMP documents and UI resources. It is not directly public, but is
  # instead server through the CloudFront Distribution
  S3CloudFrontBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If
      - PreventDelete
      - 'Retain'
      - 'Delete'
    Properties:
      AccessControl: 'Private'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogBucket
        LogFilePrefix: 's3-access'

  # S3 Bucket for storing things that should not be publicly accessible like CodePipeline artifacts
  S3PrivateBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If
      - PreventDelete
      - 'Retain'
      - 'Delete'
    Properties:
      AccessControl: 'Private'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogBucket
        LogFilePrefix: 's3-access'
      VersioningConfiguration:
        Status: 'Enabled'

  # ----------------------------------------------
  # SSM Parameter Store
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
  # ----------------------------------------------
  # S3 Bucket Urls
  S3CloudFrontBucketUrlParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} S3 CloudFront Bucket URL"
      Name: !Sub "${SsmPath}S3CloudFrontBucketUrl"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt S3CloudFrontBucket.WebsiteURL

  S3PrivateBucketIdParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AWS::StackName} S3 Private Bucket Id"
      Name: !Sub "${SsmPath}S3PrivateBucketId"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !Ref S3PrivateBucket

Outputs:
  S3LogBucketId:
    Value: !Ref S3LogBucket
  S3LogBucketUri:
    Value: !Sub "s3://${S3LogBucket}"
  S3LogBucketArn:
    Value: !GetAtt S3LogBucket.Arn
    Export:
      Name: !Sub '${Env}-S3LogBucketArn'

  S3CloudFrontBucketId:
    Value: !Ref S3CloudFrontBucket
  S3CloudFrontBucketUri:
    Value: !Sub "s3://${S3CloudFrontBucket}"
  S3CloudFrontBucketArn:
    Value: !GetAtt S3CloudFrontBucket.Arn
    Export:
      Name: !Sub '${Env}-S3CloudFrontBucketArn'

  S3PrivateBucketId:
    Value: !Ref S3PrivateBucket
    Export:
      Name: !Sub '${Env}-S3PrivateBucketId'
  S3PrivateBucketUri:
    Value: !Sub "s3://${S3PrivateBucket}"
  S3PrivateBucketArn:
    Value: !GetAtt S3PrivateBucket.Arn
    Export:
      Name: !Sub '${Env}-S3PrivateBucketArn'
