AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Builds for Dynamo table and S3 bucket that stores DMP narrative docs'

Parameters:
  AdminEmail:
    Type: 'String'

Resources:
  # ----------------------------------------------
  # Simple Queue Service (SQS). Some Lambdas write to the queue and others watch for messages
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
  # ----------------------------------------------
  SqsQueue:
    Type: 'AWS::SQS::Queue'
    # DeletionPolicy: Retain
    Properties:
      MaximumMessageSize: 128000 # bytes == 128 KB
      MessageRetentionPeriod: 604800 # seconds == 7 days

  # ----------------------------------------------
  # Simple Notification Service (SNS) topics
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
  # ----------------------------------------------
  SnsTopicDownload:
    Type: 'AWS::SNS::Topic'
    Properties:
      # For some reason AWS doesn't recognize this attribute even though its in the docs
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubDownload'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  SnsTopicNotification:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubPublish'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  SnsTopicPublication:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubNotify'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  SnsTopicEmail:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubEmail'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  # You can only give one email address at a time. If you want to send a message to
  # multiple users, you have to create multiple subscriptions
  #
  # Note that the AdminEmail address will receive a confirmation email from AWS that
  # must be manually confirmed!
  ErrorEmailSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref AdminEmail
      Protocol: 'email'
      TopicArn: !Ref SnsTopicEmail

Outputs:
  SqsQueueId:
    Value: !Ref SqsQueue
  SqsQueueArn:
    Value: !GetAtt SqsQueue.Arn

  SnsTopicDownloadArn:
    Value: !Ref SnsTopicDownload
  SnsTopicDownloadName:
    Value: !GetAtt SnsTopicDownload.TopicName
  SnsTopicNotificationArn:
    Value: !Ref SnsTopicNotification
  SnsTopicNotificationName:
    Value: !GetAtt SnsTopicNotification.TopicName
  SnsTopicPublicationArn:
    Value: !Ref SnsTopicPublication
  SnsTopicPublicationName:
    Value: !GetAtt SnsTopicPublication.TopicName
  SnsTopicEmailArn:
    Value: !Ref SnsTopicEmail
  SnsTopicEmailName:
    Value: !GetAtt SnsTopicEmail.TopicName
