AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Builds for Dynamo table and S3 bucket that stores DMP narrative docs'

Parameters:
  AppName:
    Type: 'String'

  Env:
    Type: 'String'

  SsmPath:
    Type: 'String'

  AdminEmail:
    Type: 'String'

Resources:
  # ----------------------------------------------
  # Simple Queue Service (SQS). Some Lambdas write to the queue and others watch for messages
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
  # ----------------------------------------------
  SqsQueue:
    Type: 'AWS::SQS::Queue'
    # DeletionPolicy: Retain
    Properties:
      MaximumMessageSize: 128000 # bytes == 128 KB
      MessageRetentionPeriod: 604800 # seconds == 7 days

  # Add the Table name to SSM so that our Lambdas can access it
  SqsQueueArnParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AppName}-${Env} SQS Queue"
      Name: !Sub "${SsmPath}SqsQueueArn"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt SqsQueue.Arn

  # ----------------------------------------------
  # Simple Notification Service (SNS) topics
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
  # ----------------------------------------------
  SnsTopicDownload:
    Type: 'AWS::SNS::Topic'
    Properties:
      # For some reason AWS doesn't recognize this attribute even though its in the docs
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubDownload'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  # Add the Topic name to SSM so that our Lambdas can access it
  SnsTopicDownloadParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AppName}-${Env} Download Topic"
      Name: !Sub "${SsmPath}SnsDownloadTopicName"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt SnsTopicDownload.TopicName

  SnsTopicNotification:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubPublish'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  # Add the Topic name to SSM so that our Lambdas can access it
  SnsTopicNotificationParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AppName}-${Env} Notification Topic"
      Name: !Sub "${SsmPath}SnsNotifyTopicName"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt SnsTopicNotification.TopicName

  SnsTopicPublication:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubNotify'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  # Add the Topic name to SSM so that our Lambdas can access it
  SnsTopicPublicationParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AppName}-${Env} Publication Topic"
      Name: !Sub "${SsmPath}SnsPublishTopicName"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt SnsTopicPublication.TopicName

  SnsTopicEmail:
    Type: 'AWS::SNS::Topic'
    Properties:
      # ContentBasedDeduplication: true
      DisplayName: 'DmpHubEmail'
      Subscription:
        - Protocol: 'sqs'
          Endpoint: !GetAtt SqsQueue.Arn

  # Add the Topic name to SSM so that our Lambdas can access it
  SnsTopicEmailParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub "${AppName}-${Env} Email Topic"
      Name: !Sub "${SsmPath}SnsFatalErrorTopicName"
      # Note: AWS CloudFormation does not yet support creating a SecureString parameter type.
      Type: 'String'
      Value: !GetAtt SnsTopicEmail.TopicName

  # You can only give one email address at a time. If you want to send a message to
  # multiple users, you have to create multiple subscriptions
  #
  # Note that the AdminEmail address will receive a confirmation email from AWS that
  # must be manually confirmed!
  ErrorEmailSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref AdminEmail
      Protocol: 'email'
      TopicArn: !Ref SnsTopicEmail

Outputs:
  SqsQueueId:
    Value: !Ref SqsQueue
  SqsQueueArn:
    Value: !GetAtt SqsQueue.Arn

  SnsTopicDownloadArn:
    Value: !Ref SnsTopicDownload
  SnsTopicDownloadName:
    Value: !GetAtt SnsTopicDownload.TopicName
  SnsTopicNotificationArn:
    Value: !Ref SnsTopicNotification
  SnsTopicNotificationName:
    Value: !GetAtt SnsTopicNotification.TopicName
  SnsTopicPublicationArn:
    Value: !Ref SnsTopicPublication
  SnsTopicPublicationName:
    Value: !GetAtt SnsTopicPublication.TopicName
  SnsTopicEmailArn:
    Value: !Ref SnsTopicEmail
  SnsTopicEmailName:
    Value: !GetAtt SnsTopicEmail.TopicName
