AWSTemplateFormatVersion: '2010-09-09'

Description: 'WAF for DMPTool/DMPHub'

Parameters:
  Scope:
    Type: 'String'
    Default: 'REGIONAL'
    AllowedValues:
      - 'CLOUDFRONT'
      - 'REGIONAL'

  SampledRequestsEnabled:
    Type: 'String'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  CloudWatchMetricsEnabled:
    Type: 'String'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

Resources:
  # -----------------------------------------------------------
  # Web Application Firewall (WAF) - Stops malicious actors/bots from reaching application
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_WAFv2.html
  # -----------------------------------------------------------
  WafRegional:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: !Sub "${AWS::StackName}-Cloudfront-WAF"
      DefaultAction:
        Allow: {}
      Scope: !Ref Scope
      VisibilityConfig:
        SampledRequestsEnabled: !Ref SampledRequestsEnabled
        CloudWatchMetricsEnabled: !Ref CloudWatchMetricsEnabled
        MetricName: !Sub '${AWS::StackName}-waf-metric'
      Rules:
        - Name: 'AWS-AWSManagedRulesAmazonIpReputationList'
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: 'AWS-AWSManagedRulesAmazonIpReputationList'
          Statement:
            ManagedRuleGroupStatement:
              VendorName: 'AWS'
              Name: 'AWSManagedRulesAmazonIpReputationList'
              ExcludedRules: []
        - Name: 'AWS-AWSManagedRulesCommonRuleSet'
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: 'AWS-AWSManagedRulesCommonRuleSet'
          Statement:
            ManagedRuleGroupStatement:
              VendorName: 'AWS'
              Name: 'AWSManagedRulesCommonRuleSet'
              ExcludedRules: []
        - Name: 'AWS-AWSManagedRulesKnownBadInputsRuleSet'
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: 'AWS-AWSManagedRulesKnownBadInputsRuleSet'
          Statement:
            ManagedRuleGroupStatement:
              VendorName: 'AWS'
              Name: 'AWSManagedRulesKnownBadInputsRuleSet'
              ExcludedRules: []

Outputs:
  WafId:
    Value: !GetAtt WafRegional.Id
  WafArn:
    Value: !GetAtt WafRegional.Arn
