template:
  path: 'cognito-app-client.yaml'
  type: 'file'

parameters:
  UserPoolId: !stack_output prd/regional/cognito.yaml::UserPoolId

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: 'auth'
  Env: !stack_attr sceptre_user_data.env

  ClientName: 'arizona-state'

  ClientCallbackUri: 'https://localhost:3000/callback/'

  Scopes:
    - 'https://auth.dmphub.uc3prd.cdlib.net/prd.read'
    - 'https://auth.dmphub.uc3prd.cdlib.net/prd.write'

  OnlyAllowAdminsToCreateUsers: 'false'
  UnusedAccountValidityDays: '14'
  MinimumPasswordLength: '8'

  TokenValidityUnits: 'minutes'
  AccessTokenValidity: '10'
  AuthSessionValidatyMinutes: '3'
  IdTokenValidity: '7'
  RefreshTokenValidity: '10080'

hooks:
  after_create:
    cmd: 'src/add-api-client.sh prd arizona-state http://localhost:3000/callback'
    cmd: 'aws ssm put-parameter --overwrite --name /uc3/dmp/tool/provenance/arizona-state/ror_list --type String --value "[\"https://ror.org/03efmqc40\"]"'
