template:
  path: 'cognito-app-client.yaml'
  type: 'file'

parameters:
  UserPoolId: !stack_output prd/regional/cognito.yaml::UserPoolId

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: 'auth'
  Env: !stack_attr sceptre_user_data.env

  ClientName: 'uc-boulder'

  ClientCallbackUri: 'https://localhost:3000/callback'

  OnlyAllowAdminsToCreateUsers: 'false'
  UnusedAccountValidityDays: '14'
  MinimumPasswordLength: '8'

  TokenValidityUnits: 'minutes'
  AccessTokenValidity: '10'
  AuthSessionValidatyMinutes: '3'
  IdTokenValidity: '7'
  RefreshTokenValidity: '10080'

hooks:
  after_update:
    cmd: 'src/scripts/add-api-client.sh prd uc-boulder http://localhost:3000/callback'
    cmd: 'aws ssm put-parameter --overwrite --name /uc3/dmp/tool/provenance/uc-boulder/ror_list --type String --value \'["https://ror.org/02ttsq026"]\''
