template:
  path: 'cognito-app-client.yaml'
  type: 'file'

parameters:
  UserPoolId: !stack_output stg/regional/cognito.yaml::UserPoolId

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: 'auth'
  Env: !stack_attr sceptre_user_data.env

  ClientName: 'coki'

  ClientCallbackUri: 'https://localhost:3000/callback'

  OnlyAllowAdminsToCreateUsers: 'false'
  UnusedAccountValidityDays: '14'
  MinimumPasswordLength: '8'

  TokenValidityUnits: 'minutes'
  AccessTokenValidity: '10'
  AuthSessionValidatyMinutes: '3'
  IdTokenValidity: '7'
  RefreshTokenValidity: '10080'

  Scopes:
    - 'https://auth.dmphub.uc3stg.cdlib.net/stg.data-transfer'

hooks:
  after_update:
    cmd: 'src/add-api-client.sh stg coki http://localhost:3000/callback'
    cmd: 'aws ssm put-parameter --overwrite --name /uc3/dmp/tool/provenance/coki/ror_list --type String --value "[]"'
