template:
  path: appsync.yaml
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env
  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: !stack_attr sceptre_user_data.subdomain

  CertificateArn: !stack_output dev/cert.yaml::AlbCertificateArn
  CognitoUserPoolId: !stack_output dev/cognito.yaml::SystemsUserPoolId

  S3BucketUri: !stack_output dev/data.yaml::S3BucketUri

  GetDmpLambdaArn: !stack_output dev/lambdas.yaml::GetDmpLambdaFunctionArn
  AddDmpLambdaArn: !stack_output dev/lambdas.yaml::AddDmpLambdaFunctionArn
