template:
  path: 'cloudfront.yaml'
  type: 'file'

dependencies:
  - 'dev/cognito.yaml'

parameters:
  S3PrivateBucketId: !stack_output dev/s3.yaml::S3PrivateBucketId

  S3PublicBucketId: !stack_output dev/s3.yaml::S3PublicBucketId
  S3PublicBucketArn: !stack_output dev/s3.yaml::S3PublicBucketArn

  CertificateArn: !stack_output dev/cert.yaml::CognitoCertificateArn

  WafArn: !stack_output dev/waf.yaml::WafArn
