template:
  path: 'cloud-front.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  CloudFrontWafArn: !stack_output dev/globals.yaml::WafArn

  S3BucketId: !stack_output dev/data.yaml::S3BucketId

  S3LogBucketId: !stack_output dev/logs.yaml::S3LogBucketId

  DomainName: !stack_attr sceptre_user_data.domain
