template:
  path: code-pipeline-setup.yaml
  type: file

parameters:
  VpcId: !stack_output_external cdl-uc3-dev-vpc-stack::vpc

  AppName: !stack_attr sceptre_user_data.app_name

  LogGroupArn: !stack_output dev/logs.yaml::LogGroupArn

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn
