template:
  path: 'cognito.yaml'
  type: 'file'

dependencies:
  - 'dev/route53.yaml'

parameters:
  HostedZoneId: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  CertificateArn: !stack_output dev/cert.yaml::CognitoCertificateArn

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: !stack_attr sceptre_user_data.subdomain

  Env: !stack_attr sceptre_user_data.env

  DmptoolCallbackUri: 'https://dmptool-dev.cdlib.org/callback'
