template_bucket_name: uc3-dmp-hub-cf-bucket

stack_tags:
  Program: 'uc3'
  Service: 'dmp'
  Subservice: 'hub'
  Environment: 'dev'
  CodeRepo: 'https://github.com/CDLUC3/dmp-hub-cfn'
  Contact: 'briley'

sceptre_user_data:
  domain: !ssm_parameter /uc3/dev/HostedZoneName
  subdomain: 'dmphub'

  # Some resources like the Cognito UserPool don't get the normal Sceptre stack name
  resource_name_prefix: 'uc3-dmp-hub'
  env: 'dev'
  ssm_path: '/uc3/dmp/hub/dev/'
  lambda_code_dir: '~/Documents/workspace'

  rails_env: 'development'
  rails_log_level: 'debug'
  rails_port: '80'
