template:
  path: globals.yaml
  type: file

# Cloudfront requires that some resources be built in the us-east-1 region
# See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webacl.html#cfn-wafv2-webacl-scope
region: us-east-1

parameters:
  # Use the HostedZoneId stored in SSM since this template is not in us-west-2 and will not
  # have access to !external_stack_output for stacks in that region
  HostedZoneId: !ssm_parameter /uc3/HostedZoneId
  DomainName: !stack_attr sceptre_user_data.domain
