template:
  path: lambdas-direct.yaml.j2
  type: file

parameters:
  VpcId: !stack_output_external cdl-uc3-dev-vpc-stack::vpc
  Subnets:
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2a
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2b
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2c

  CodeBuildSecurityGroupId: !stack_output dev/code-pipeline-setup.yaml::CodeBuildSecurityGroupId

  Env: !stack_attr sceptre_user_data.env

  CodePipelineIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodePipelineIAMRoleArn
  CodeBuildIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodeBuildIAMRoleArn
  CodeDeployIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodeDeployIAMRoleArn

  S3CodePipelineBucket: !stack_output dev/code-pipeline-setup.yaml::CodePipelineS3BucketId
  S3LambdaCodeSigningBucketId: !stack_output dev/code-pipeline-setup.yaml::S3LambdaCodeSigningBucketId
  S3RepositoryBucket: !stack_output dev/code-pipeline-setup.yaml::S3LambdaRepositoryBucketId

  # LambdaCodeSigningConfigArn: !stack_output dev/code-pipeline-setup.yaml::CodeSigningConfigArn
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  RepositoryBranchToMonitor: 'main'

  LogGroupId: !stack_output dev/logs.yaml::LogGroupId

  S3BucketId: !stack_output dev/data.yaml::S3BucketId
  S3BucketArn: !stack_output dev/data.yaml::S3BucketArn

  DynamoTableArn: !stack_output dev/data.yaml::DynamoTableArn
  DynamoTableName: !stack_output dev/data.yaml::DynamoTableName

  SnsTopicEmailArn: !stack_output dev/sqs.yaml::SnsTopicEmailArn
