template:
  path: lambdas-api.yaml.j2
  type: file

parameters:
  VpcId: !stack_output_external cdl-uc3-dev-vpc-stack::vpc
  Subnets:
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2a
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2b
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2c

  CodeBuildSecurityGroupId: !stack_output dev/code-pipeline-setup.yaml::CodeBuildSecurityGroupId

  Env: !stack_attr sceptre_user_data.env
  DomainName: !stack_attr sceptre_user_data.domain
  DmpIdShoulder: !ssm_parameter /uc3/dmp/hub/dev/EzidShoulder

  CodePipelineIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodePipelineIAMRoleArn
  CodeBuildIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodeBuildIAMRoleArn
  CodeDeployIAMRoleArn: !stack_output dev/code-pipeline-setup.yaml::CodeDeployIAMRoleArn

  S3CodePipelineBucket: !stack_output dev/code-pipeline-setup.yaml::CodePipelineS3BucketId
  S3LambdaCodeSigningBucketId: !stack_output dev/code-pipeline-setup.yaml::S3LambdaCodeSigningBucketId
  S3RepositoryBucket: !stack_output dev/code-pipeline-setup.yaml::S3LambdaRepositoryBucketId

  # LambdaCodeSigningConfigArn: !stack_output dev/code-pipeline-setup.yaml::CodeSigningConfigArn
  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  RepositoryBranchToMonitor: 'main'

  LogGroupId: !stack_output dev/logs.yaml::LogGroupId

  AuthorizerFunctionId: !stack_output dev/lambdas-direct.yaml::AuthorizerFunctionId
  ResponderFunctionId: !stack_output dev/lambdas-direct.yaml::ResponderFunctionId
  ValidatorFunctionId: !stack_output dev/lambdas-direct.yaml::ValidatorFunctionId

  DynamoTableName: !stack_output dev/data.yaml::DynamoTableName
  DynamoTableArn: !stack_output dev/data.yaml::DynamoTableArn
  S3BucketArn: !stack_output dev/data.yaml::S3BucketArn
  SqsQueueArn: !stack_output dev/sqs.yaml::SqsQueueArn