template:
  path: 'pipeline.yaml'
  type: 'file'

parameters:
  VpcId: !stack_output_external cdl-uc3-dev-vpc-stack::vpc
  Subnets:
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2a
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2b
    - !stack_output_external cdl-uc3-dev-privatesubnet-stack::privatesubnet2c

  DomainName: !stack_attr sceptre_user_data.domain
  Subdomain: !stack_attr sceptre_user_data.subdomain
  Env: !stack_attr sceptre_user_data.env

  # We need to add a special tag to the CodeBuild SecGroup so that it does not
  # generate an alarm after the EC2 instance used by CodeBuild is removed.
  # So, we need to pass in our normal tags here so that the SecGroup will have all of them
  Program: !stack_attr stack_tags.Program
  Service: !stack_attr stack_tags.Service
  Subservice: !stack_attr stack_tags.Subservice

  CodeStarConnectionArn: !ssm_parameter /uc3/CodeStarConnectionArn

  EcsClusterName: !stack_output dev/fargate.yaml::EcsFargateClusterId
  EcsServiceName: !stack_output dev/fargate.yaml::EcsServiceName

  EcrRepositoryUri: !stack_output dev/data.yaml::EcrRepositoryUri
  EcrRepositoryName: !stack_output dev/data.yaml::EcrRepositoryName

  LogGroupId: !stack_output dev/logs.yaml::LogGroupId
  LogGroupArn: !stack_output dev/logs.yaml::LogGroupArn

  S3ArtifactBucketId: !stack_attr template_bucket_name
  S3LogBucketId: !stack_output dev/logs.yaml::S3LogBucketId

  # The branches to monitor for changes.
  BranchToMonitor: 'main'

  # Environment variables required to build the Docker image
  RailsEnv: !stack_attr sceptre_user_data.rails_env
  RailsLogLevel: !stack_attr sceptre_user_data.rails_log_level
  RailsPort: !stack_attr sceptre_user_data.rails_port

  RdsAddress: !stack_output dev/data.yaml::RdsAddress
  RdsPort: !stack_output dev/data.yaml::RdsPort
  RdsName: !stack_output dev/data.yaml::RdsName
  RdsUsername: !ssm_parameter '/uc3/dmp/hub/dev/RdsUsername'
  RdsPassword: !ssm_parameter '/uc3/dmp/hub/dev/RdsPassword'
