template:
  path: 'rest-api.yaml.j2'
  type: 'file'

parameters:
  AppName: !stack_attr sceptre_user_data.app_name
  Env: !stack_attr sceptre_user_data.env
  DomainName: !stack_attr sceptre_user_data.domain

  ApiStageName: 'v0'

  # Lambda Function IDs and ARNs are pulled into the template directly using CF's ImportValue
  # function because jinja2 does not natively support the inclusion of j2 templates using a
  # relative path. (e.g. '../../templates/includes.js')
  LambdaFunctionStackName: !stack_output dev/lambdas-api.yaml::LambdaApiStackName

  VpcId: !stack_output_external cdl-uc3-dev-vpc-stack::vpc

  HostedZoneId: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  CertificateArn: !stack_output dev/globals.yaml::CertificateArn

  SystemsUserPoolId: !stack_output dev/cognito.yaml::SystemsUserPoolId
  SystemsUserPoolArn: !stack_output dev/cognito.yaml::SystemsUserPoolArn

  S3LogBucketId: !stack_output dev/logs.yaml::S3LogBucketId
  ApplicationLogGroupId: !stack_output dev/logs.yaml::LogGroupId
  ApplicationLogGroupArn: !stack_output dev/logs.yaml::LogGroupArn
