template:
  path: 'route53.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone_id

  Domain: !stack_attr sceptre_user_data.domain

  AlbDnsName: !stack_output dev/alb.yaml::AlbDnsName
  AlbHostedZoneId: !stack_output dev/alb.yaml::AlbHostedZoneId
