template:
  path: 'route53.yaml'
  type: 'file'

parameters:
  HostedZoneId: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  Domain: !stack_attr sceptre_user_data.domain
  Subdomain: !stack_attr sceptre_user_data.subdomain

  AlbDnsName: !stack_output dev/alb.yaml::AlbDnsName
  AlbHostedZoneId: !stack_output dev/alb.yaml::AlbHostedZoneId
