template:
  path: sqs.yaml
  type: file

parameters:
  AppName: !stack_attr sceptre_user_data.app_name
  Env: !stack_attr sceptre_user_data.env
  SsmPath: !stack_attr sceptre_user_data.ssm_path
  AdminEmail: !ssm_parameter /uc3/dmp/hub/dev/AdminEmail
