source "https://rubygems.org"

ruby '>= 3.2'

gem 'httparty'
gem 'json-schema'

group :test do
  gem "rspec"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "aws-sdk-dynamodb"
  gem "aws-sdk-s3"
  gem "aws-sdk-sns"
  gem "aws-sdk-ssm"
  gem "opensearch-ruby"

  gem "uc3-dmp-api-core"
  gem "uc3-dmp-citation"
  gem "uc3-dmp-cloudwatch"
  gem "uc3-dmp-cognito"
  gem "uc3-dmp-dynamo"
  gem "uc3-dmp-event-bridge"
  gem "uc3-dmp-external-api"
  gem "uc3-dmp-id"
  gem "uc3-dmp-provenance"
  gem "uc3-dmp-rds"
  gem "uc3-dmp-s3"
end
