source "https://rubygems.org"

gem "httparty"
gem "json-schema"

group :test do
  gem "rspec"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "aws-sdk-dynamodb"
  gem "aws-sdk-s3"
  gem "aws-sdk-sns"
  gem "aws-sdk-ssm"
end
