version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "uc3-dmp-hub-dev-regional-lambdas"
s3_bucket = ""
s3_prefix = "uc3-dmp-hub-dev-regional-lambdas"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []
tags = [
  "Program=uc3",
  "Service=dmp",
  "Subservice=hub",
  "Environment=dev",
  "CodeRepo=https://github.com/CDLUC3/dmp-hub-cfn",
  "Contact=briley"
]
