# frozen_string_literal: true

source 'https://rubygems.org'

# No need to include any AWS SDK gems here since the Lambda functions have access
# to them by default
gem 'activerecord'
gem 'active_record_simple_execute'
gem 'mysql2'

gem 'uc3-dmp-api-core'
gem 'uc3-dmp-rds'

group :test do
  gem "rspec"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rspec"
end
