# frozen_string_literal: true

source 'https://rubygems.org'

# No need to include any AWS SDK gems here since the Lambda functions have access
# to them by default
# gem 'active_record_simple_execute'
# gem 'mysql2'
# gem 'aws-sdk-sns'
# gem 'aws-sdk-ssm'

gem 'uc3-dmp-api-core', path: '../../gems/uc3-dmp-api-core'
