# frozen_string_literal: true

source "https://rubygems.org"

# This module provides a framework for message digest libraries. https://github.com/ruby/digest
gem 'digest'

# Rubyzip is a ruby library for reading and writing zip files. https://github.com/rubyzip/rubyzip
gem 'rubyzip'
gem 'zip'

# Sanitize and Execute your raw SQL queries in ActiveRecord and Rails with a much more intuitive and
# shortened syntax. https://github.com/westonganger/active_record_simple_execute
gem 'active_record_simple_execute'

# Trilogy is a client library for MySQL-compatible database servers, designed for performance, flexibility,
# and ease of embedding. https://github.com/trilogy-libraries/trilogy
gem 'trilogy'

# Custom UC3 developed helper gems to standardize Lambda internals
gem 'uc3-dmp-api-core'
gem 'uc3-dmp-cloudwatch'
gem 'uc3-dmp-external-api'